// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/dailybalancegrant"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// DailyBalanceGrantUpdate is the builder for updating DailyBalanceGrant entities.
type DailyBalanceGrantUpdate struct {
	config
	hooks    []Hook
	mutation *DailyBalanceGrantMutation
}

// Where appends a list predicates to the DailyBalanceGrantUpdate builder.
func (_u *DailyBalanceGrantUpdate) Where(ps ...predicate.DailyBalanceGrant) *DailyBalanceGrantUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *DailyBalanceGrantUpdate) SetUserID(v int64) *DailyBalanceGrantUpdate {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *DailyBalanceGrantUpdate) SetNillableUserID(v *int64) *DailyBalanceGrantUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *DailyBalanceGrantUpdate) AddUserID(v int64) *DailyBalanceGrantUpdate {
	_u.mutation.AddUserID(v)
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *DailyBalanceGrantUpdate) SetGroupID(v int64) *DailyBalanceGrantUpdate {
	_u.mutation.ResetGroupID()
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *DailyBalanceGrantUpdate) SetNillableGroupID(v *int64) *DailyBalanceGrantUpdate {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// AddGroupID adds value to the "group_id" field.
func (_u *DailyBalanceGrantUpdate) AddGroupID(v int64) *DailyBalanceGrantUpdate {
	_u.mutation.AddGroupID(v)
	return _u
}

// SetAmount sets the "amount" field.
func (_u *DailyBalanceGrantUpdate) SetAmount(v float64) *DailyBalanceGrantUpdate {
	_u.mutation.ResetAmount()
	_u.mutation.SetAmount(v)
	return _u
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_u *DailyBalanceGrantUpdate) SetNillableAmount(v *float64) *DailyBalanceGrantUpdate {
	if v != nil {
		_u.SetAmount(*v)
	}
	return _u
}

// AddAmount adds value to the "amount" field.
func (_u *DailyBalanceGrantUpdate) AddAmount(v float64) *DailyBalanceGrantUpdate {
	_u.mutation.AddAmount(v)
	return _u
}

// SetRemaining sets the "remaining" field.
func (_u *DailyBalanceGrantUpdate) SetRemaining(v float64) *DailyBalanceGrantUpdate {
	_u.mutation.ResetRemaining()
	_u.mutation.SetRemaining(v)
	return _u
}

// SetNillableRemaining sets the "remaining" field if the given value is not nil.
func (_u *DailyBalanceGrantUpdate) SetNillableRemaining(v *float64) *DailyBalanceGrantUpdate {
	if v != nil {
		_u.SetRemaining(*v)
	}
	return _u
}

// AddRemaining adds value to the "remaining" field.
func (_u *DailyBalanceGrantUpdate) AddRemaining(v float64) *DailyBalanceGrantUpdate {
	_u.mutation.AddRemaining(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *DailyBalanceGrantUpdate) SetStatus(v string) *DailyBalanceGrantUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *DailyBalanceGrantUpdate) SetNillableStatus(v *string) *DailyBalanceGrantUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetSource sets the "source" field.
func (_u *DailyBalanceGrantUpdate) SetSource(v string) *DailyBalanceGrantUpdate {
	_u.mutation.SetSource(v)
	return _u
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (_u *DailyBalanceGrantUpdate) SetNillableSource(v *string) *DailyBalanceGrantUpdate {
	if v != nil {
		_u.SetSource(*v)
	}
	return _u
}

// SetSourceRef sets the "source_ref" field.
func (_u *DailyBalanceGrantUpdate) SetSourceRef(v string) *DailyBalanceGrantUpdate {
	_u.mutation.SetSourceRef(v)
	return _u
}

// SetNillableSourceRef sets the "source_ref" field if the given value is not nil.
func (_u *DailyBalanceGrantUpdate) SetNillableSourceRef(v *string) *DailyBalanceGrantUpdate {
	if v != nil {
		_u.SetSourceRef(*v)
	}
	return _u
}

// ClearSourceRef clears the value of the "source_ref" field.
func (_u *DailyBalanceGrantUpdate) ClearSourceRef() *DailyBalanceGrantUpdate {
	_u.mutation.ClearSourceRef()
	return _u
}

// SetGrantedAt sets the "granted_at" field.
func (_u *DailyBalanceGrantUpdate) SetGrantedAt(v time.Time) *DailyBalanceGrantUpdate {
	_u.mutation.SetGrantedAt(v)
	return _u
}

// SetNillableGrantedAt sets the "granted_at" field if the given value is not nil.
func (_u *DailyBalanceGrantUpdate) SetNillableGrantedAt(v *time.Time) *DailyBalanceGrantUpdate {
	if v != nil {
		_u.SetGrantedAt(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *DailyBalanceGrantUpdate) SetExpiresAt(v time.Time) *DailyBalanceGrantUpdate {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *DailyBalanceGrantUpdate) SetNillableExpiresAt(v *time.Time) *DailyBalanceGrantUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// Mutation returns the DailyBalanceGrantMutation object of the builder.
func (_u *DailyBalanceGrantUpdate) Mutation() *DailyBalanceGrantMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *DailyBalanceGrantUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DailyBalanceGrantUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *DailyBalanceGrantUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DailyBalanceGrantUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DailyBalanceGrantUpdate) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := dailybalancegrant.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "DailyBalanceGrant.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Source(); ok {
		if err := dailybalancegrant.SourceValidator(v); err != nil {
			return &ValidationError{Name: "source", err: fmt.Errorf(`ent: validator failed for field "DailyBalanceGrant.source": %w`, err)}
		}
	}
	return nil
}

func (_u *DailyBalanceGrantUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(dailybalancegrant.Table, dailybalancegrant.Columns, sqlgraph.NewFieldSpec(dailybalancegrant.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(dailybalancegrant.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(dailybalancegrant.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.GroupID(); ok {
		_spec.SetField(dailybalancegrant.FieldGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedGroupID(); ok {
		_spec.AddField(dailybalancegrant.FieldGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Amount(); ok {
		_spec.SetField(dailybalancegrant.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAmount(); ok {
		_spec.AddField(dailybalancegrant.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Remaining(); ok {
		_spec.SetField(dailybalancegrant.FieldRemaining, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedRemaining(); ok {
		_spec.AddField(dailybalancegrant.FieldRemaining, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(dailybalancegrant.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Source(); ok {
		_spec.SetField(dailybalancegrant.FieldSource, field.TypeString, value)
	}
	if value, ok := _u.mutation.SourceRef(); ok {
		_spec.SetField(dailybalancegrant.FieldSourceRef, field.TypeString, value)
	}
	if _u.mutation.SourceRefCleared() {
		_spec.ClearField(dailybalancegrant.FieldSourceRef, field.TypeString)
	}
	if value, ok := _u.mutation.GrantedAt(); ok {
		_spec.SetField(dailybalancegrant.FieldGrantedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(dailybalancegrant.FieldExpiresAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{dailybalancegrant.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// DailyBalanceGrantUpdateOne is the builder for updating a single DailyBalanceGrant entity.
type DailyBalanceGrantUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *DailyBalanceGrantMutation
}

// SetUserID sets the "user_id" field.
func (_u *DailyBalanceGrantUpdateOne) SetUserID(v int64) *DailyBalanceGrantUpdateOne {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *DailyBalanceGrantUpdateOne) SetNillableUserID(v *int64) *DailyBalanceGrantUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *DailyBalanceGrantUpdateOne) AddUserID(v int64) *DailyBalanceGrantUpdateOne {
	_u.mutation.AddUserID(v)
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *DailyBalanceGrantUpdateOne) SetGroupID(v int64) *DailyBalanceGrantUpdateOne {
	_u.mutation.ResetGroupID()
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *DailyBalanceGrantUpdateOne) SetNillableGroupID(v *int64) *DailyBalanceGrantUpdateOne {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// AddGroupID adds value to the "group_id" field.
func (_u *DailyBalanceGrantUpdateOne) AddGroupID(v int64) *DailyBalanceGrantUpdateOne {
	_u.mutation.AddGroupID(v)
	return _u
}

// SetAmount sets the "amount" field.
func (_u *DailyBalanceGrantUpdateOne) SetAmount(v float64) *DailyBalanceGrantUpdateOne {
	_u.mutation.ResetAmount()
	_u.mutation.SetAmount(v)
	return _u
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_u *DailyBalanceGrantUpdateOne) SetNillableAmount(v *float64) *DailyBalanceGrantUpdateOne {
	if v != nil {
		_u.SetAmount(*v)
	}
	return _u
}

// AddAmount adds value to the "amount" field.
func (_u *DailyBalanceGrantUpdateOne) AddAmount(v float64) *DailyBalanceGrantUpdateOne {
	_u.mutation.AddAmount(v)
	return _u
}

// SetRemaining sets the "remaining" field.
func (_u *DailyBalanceGrantUpdateOne) SetRemaining(v float64) *DailyBalanceGrantUpdateOne {
	_u.mutation.ResetRemaining()
	_u.mutation.SetRemaining(v)
	return _u
}

// SetNillableRemaining sets the "remaining" field if the given value is not nil.
func (_u *DailyBalanceGrantUpdateOne) SetNillableRemaining(v *float64) *DailyBalanceGrantUpdateOne {
	if v != nil {
		_u.SetRemaining(*v)
	}
	return _u
}

// AddRemaining adds value to the "remaining" field.
func (_u *DailyBalanceGrantUpdateOne) AddRemaining(v float64) *DailyBalanceGrantUpdateOne {
	_u.mutation.AddRemaining(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *DailyBalanceGrantUpdateOne) SetStatus(v string) *DailyBalanceGrantUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *DailyBalanceGrantUpdateOne) SetNillableStatus(v *string) *DailyBalanceGrantUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetSource sets the "source" field.
func (_u *DailyBalanceGrantUpdateOne) SetSource(v string) *DailyBalanceGrantUpdateOne {
	_u.mutation.SetSource(v)
	return _u
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (_u *DailyBalanceGrantUpdateOne) SetNillableSource(v *string) *DailyBalanceGrantUpdateOne {
	if v != nil {
		_u.SetSource(*v)
	}
	return _u
}

// SetSourceRef sets the "source_ref" field.
func (_u *DailyBalanceGrantUpdateOne) SetSourceRef(v string) *DailyBalanceGrantUpdateOne {
	_u.mutation.SetSourceRef(v)
	return _u
}

// SetNillableSourceRef sets the "source_ref" field if the given value is not nil.
func (_u *DailyBalanceGrantUpdateOne) SetNillableSourceRef(v *string) *DailyBalanceGrantUpdateOne {
	if v != nil {
		_u.SetSourceRef(*v)
	}
	return _u
}

// ClearSourceRef clears the value of the "source_ref" field.
func (_u *DailyBalanceGrantUpdateOne) ClearSourceRef() *DailyBalanceGrantUpdateOne {
	_u.mutation.ClearSourceRef()
	return _u
}

// SetGrantedAt sets the "granted_at" field.
func (_u *DailyBalanceGrantUpdateOne) SetGrantedAt(v time.Time) *DailyBalanceGrantUpdateOne {
	_u.mutation.SetGrantedAt(v)
	return _u
}

// SetNillableGrantedAt sets the "granted_at" field if the given value is not nil.
func (_u *DailyBalanceGrantUpdateOne) SetNillableGrantedAt(v *time.Time) *DailyBalanceGrantUpdateOne {
	if v != nil {
		_u.SetGrantedAt(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *DailyBalanceGrantUpdateOne) SetExpiresAt(v time.Time) *DailyBalanceGrantUpdateOne {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *DailyBalanceGrantUpdateOne) SetNillableExpiresAt(v *time.Time) *DailyBalanceGrantUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// Mutation returns the DailyBalanceGrantMutation object of the builder.
func (_u *DailyBalanceGrantUpdateOne) Mutation() *DailyBalanceGrantMutation {
	return _u.mutation
}

// Where appends a list predicates to the DailyBalanceGrantUpdate builder.
func (_u *DailyBalanceGrantUpdateOne) Where(ps ...predicate.DailyBalanceGrant) *DailyBalanceGrantUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *DailyBalanceGrantUpdateOne) Select(field string, fields ...string) *DailyBalanceGrantUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated DailyBalanceGrant entity.
func (_u *DailyBalanceGrantUpdateOne) Save(ctx context.Context) (*DailyBalanceGrant, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DailyBalanceGrantUpdateOne) SaveX(ctx context.Context) *DailyBalanceGrant {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *DailyBalanceGrantUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DailyBalanceGrantUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DailyBalanceGrantUpdateOne) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := dailybalancegrant.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "DailyBalanceGrant.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Source(); ok {
		if err := dailybalancegrant.SourceValidator(v); err != nil {
			return &ValidationError{Name: "source", err: fmt.Errorf(`ent: validator failed for field "DailyBalanceGrant.source": %w`, err)}
		}
	}
	return nil
}

func (_u *DailyBalanceGrantUpdateOne) sqlSave(ctx context.Context) (_node *DailyBalanceGrant, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(dailybalancegrant.Table, dailybalancegrant.Columns, sqlgraph.NewFieldSpec(dailybalancegrant.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "DailyBalanceGrant.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, dailybalancegrant.FieldID)
		for _, f := range fields {
			if !dailybalancegrant.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != dailybalancegrant.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(dailybalancegrant.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(dailybalancegrant.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.GroupID(); ok {
		_spec.SetField(dailybalancegrant.FieldGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedGroupID(); ok {
		_spec.AddField(dailybalancegrant.FieldGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Amount(); ok {
		_spec.SetField(dailybalancegrant.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAmount(); ok {
		_spec.AddField(dailybalancegrant.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Remaining(); ok {
		_spec.SetField(dailybalancegrant.FieldRemaining, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedRemaining(); ok {
		_spec.AddField(dailybalancegrant.FieldRemaining, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(dailybalancegrant.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Source(); ok {
		_spec.SetField(dailybalancegrant.FieldSource, field.TypeString, value)
	}
	if value, ok := _u.mutation.SourceRef(); ok {
		_spec.SetField(dailybalancegrant.FieldSourceRef, field.TypeString, value)
	}
	if _u.mutation.SourceRefCleared() {
		_spec.ClearField(dailybalancegrant.FieldSourceRef, field.TypeString)
	}
	if value, ok := _u.mutation.GrantedAt(); ok {
		_spec.SetField(dailybalancegrant.FieldGrantedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(dailybalancegrant.FieldExpiresAt, field.TypeTime, value)
	}
	_node = &DailyBalanceGrant{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{dailybalancegrant.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
