// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/dailybalancegrant"
)

// DailyBalanceGrant is the model entity for the DailyBalanceGrant schema.
type DailyBalanceGrant struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int64 `json:"user_id,omitempty"`
	// GroupID holds the value of the "group_id" field.
	GroupID int64 `json:"group_id,omitempty"`
	// 充值原始金额
	Amount float64 `json:"amount,omitempty"`
	// 剩余可用，原子递减至 0
	Remaining float64 `json:"remaining,omitempty"`
	// active / exhausted / expired
	Status string `json:"status,omitempty"`
	// admin / redeem
	Source string `json:"source,omitempty"`
	// 兑换码 code 或操作者标识，便于审计
	SourceRef *string `json:"source_ref,omitempty"`
	// GrantedAt holds the value of the "granted_at" field.
	GrantedAt time.Time `json:"granted_at,omitempty"`
	// granted_at + 24h
	ExpiresAt time.Time `json:"expires_at,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt    time.Time `json:"created_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*DailyBalanceGrant) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case dailybalancegrant.FieldAmount, dailybalancegrant.FieldRemaining:
			values[i] = new(sql.NullFloat64)
		case dailybalancegrant.FieldID, dailybalancegrant.FieldUserID, dailybalancegrant.FieldGroupID:
			values[i] = new(sql.NullInt64)
		case dailybalancegrant.FieldStatus, dailybalancegrant.FieldSource, dailybalancegrant.FieldSourceRef:
			values[i] = new(sql.NullString)
		case dailybalancegrant.FieldGrantedAt, dailybalancegrant.FieldExpiresAt, dailybalancegrant.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the DailyBalanceGrant fields.
func (_m *DailyBalanceGrant) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case dailybalancegrant.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case dailybalancegrant.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case dailybalancegrant.FieldGroupID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field group_id", values[i])
			} else if value.Valid {
				_m.GroupID = value.Int64
			}
		case dailybalancegrant.FieldAmount:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field amount", values[i])
			} else if value.Valid {
				_m.Amount = value.Float64
			}
		case dailybalancegrant.FieldRemaining:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field remaining", values[i])
			} else if value.Valid {
				_m.Remaining = value.Float64
			}
		case dailybalancegrant.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case dailybalancegrant.FieldSource:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field source", values[i])
			} else if value.Valid {
				_m.Source = value.String
			}
		case dailybalancegrant.FieldSourceRef:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field source_ref", values[i])
			} else if value.Valid {
				_m.SourceRef = new(string)
				*_m.SourceRef = value.String
			}
		case dailybalancegrant.FieldGrantedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field granted_at", values[i])
			} else if value.Valid {
				_m.GrantedAt = value.Time
			}
		case dailybalancegrant.FieldExpiresAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field expires_at", values[i])
			} else if value.Valid {
				_m.ExpiresAt = value.Time
			}
		case dailybalancegrant.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the DailyBalanceGrant.
// This includes values selected through modifiers, order, etc.
func (_m *DailyBalanceGrant) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this DailyBalanceGrant.
// Note that you need to call DailyBalanceGrant.Unwrap() before calling this method if this DailyBalanceGrant
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *DailyBalanceGrant) Update() *DailyBalanceGrantUpdateOne {
	return NewDailyBalanceGrantClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the DailyBalanceGrant entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *DailyBalanceGrant) Unwrap() *DailyBalanceGrant {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: DailyBalanceGrant is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *DailyBalanceGrant) String() string {
	var builder strings.Builder
	builder.WriteString("DailyBalanceGrant(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("group_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.GroupID))
	builder.WriteString(", ")
	builder.WriteString("amount=")
	builder.WriteString(fmt.Sprintf("%v", _m.Amount))
	builder.WriteString(", ")
	builder.WriteString("remaining=")
	builder.WriteString(fmt.Sprintf("%v", _m.Remaining))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("source=")
	builder.WriteString(_m.Source)
	builder.WriteString(", ")
	if v := _m.SourceRef; v != nil {
		builder.WriteString("source_ref=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("granted_at=")
	builder.WriteString(_m.GrantedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("expires_at=")
	builder.WriteString(_m.ExpiresAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// DailyBalanceGrants is a parsable slice of DailyBalanceGrant.
type DailyBalanceGrants []*DailyBalanceGrant
