// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/dailybalancegrant"
)

// DailyBalanceGrantCreate is the builder for creating a DailyBalanceGrant entity.
type DailyBalanceGrantCreate struct {
	config
	mutation *DailyBalanceGrantMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetUserID sets the "user_id" field.
func (_c *DailyBalanceGrantCreate) SetUserID(v int64) *DailyBalanceGrantCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetGroupID sets the "group_id" field.
func (_c *DailyBalanceGrantCreate) SetGroupID(v int64) *DailyBalanceGrantCreate {
	_c.mutation.SetGroupID(v)
	return _c
}

// SetAmount sets the "amount" field.
func (_c *DailyBalanceGrantCreate) SetAmount(v float64) *DailyBalanceGrantCreate {
	_c.mutation.SetAmount(v)
	return _c
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_c *DailyBalanceGrantCreate) SetNillableAmount(v *float64) *DailyBalanceGrantCreate {
	if v != nil {
		_c.SetAmount(*v)
	}
	return _c
}

// SetRemaining sets the "remaining" field.
func (_c *DailyBalanceGrantCreate) SetRemaining(v float64) *DailyBalanceGrantCreate {
	_c.mutation.SetRemaining(v)
	return _c
}

// SetNillableRemaining sets the "remaining" field if the given value is not nil.
func (_c *DailyBalanceGrantCreate) SetNillableRemaining(v *float64) *DailyBalanceGrantCreate {
	if v != nil {
		_c.SetRemaining(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *DailyBalanceGrantCreate) SetStatus(v string) *DailyBalanceGrantCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *DailyBalanceGrantCreate) SetNillableStatus(v *string) *DailyBalanceGrantCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetSource sets the "source" field.
func (_c *DailyBalanceGrantCreate) SetSource(v string) *DailyBalanceGrantCreate {
	_c.mutation.SetSource(v)
	return _c
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (_c *DailyBalanceGrantCreate) SetNillableSource(v *string) *DailyBalanceGrantCreate {
	if v != nil {
		_c.SetSource(*v)
	}
	return _c
}

// SetSourceRef sets the "source_ref" field.
func (_c *DailyBalanceGrantCreate) SetSourceRef(v string) *DailyBalanceGrantCreate {
	_c.mutation.SetSourceRef(v)
	return _c
}

// SetNillableSourceRef sets the "source_ref" field if the given value is not nil.
func (_c *DailyBalanceGrantCreate) SetNillableSourceRef(v *string) *DailyBalanceGrantCreate {
	if v != nil {
		_c.SetSourceRef(*v)
	}
	return _c
}

// SetGrantedAt sets the "granted_at" field.
func (_c *DailyBalanceGrantCreate) SetGrantedAt(v time.Time) *DailyBalanceGrantCreate {
	_c.mutation.SetGrantedAt(v)
	return _c
}

// SetNillableGrantedAt sets the "granted_at" field if the given value is not nil.
func (_c *DailyBalanceGrantCreate) SetNillableGrantedAt(v *time.Time) *DailyBalanceGrantCreate {
	if v != nil {
		_c.SetGrantedAt(*v)
	}
	return _c
}

// SetExpiresAt sets the "expires_at" field.
func (_c *DailyBalanceGrantCreate) SetExpiresAt(v time.Time) *DailyBalanceGrantCreate {
	_c.mutation.SetExpiresAt(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *DailyBalanceGrantCreate) SetCreatedAt(v time.Time) *DailyBalanceGrantCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *DailyBalanceGrantCreate) SetNillableCreatedAt(v *time.Time) *DailyBalanceGrantCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// Mutation returns the DailyBalanceGrantMutation object of the builder.
func (_c *DailyBalanceGrantCreate) Mutation() *DailyBalanceGrantMutation {
	return _c.mutation
}

// Save creates the DailyBalanceGrant in the database.
func (_c *DailyBalanceGrantCreate) Save(ctx context.Context) (*DailyBalanceGrant, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *DailyBalanceGrantCreate) SaveX(ctx context.Context) *DailyBalanceGrant {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DailyBalanceGrantCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DailyBalanceGrantCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *DailyBalanceGrantCreate) defaults() {
	if _, ok := _c.mutation.Amount(); !ok {
		v := dailybalancegrant.DefaultAmount
		_c.mutation.SetAmount(v)
	}
	if _, ok := _c.mutation.Remaining(); !ok {
		v := dailybalancegrant.DefaultRemaining
		_c.mutation.SetRemaining(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := dailybalancegrant.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.Source(); !ok {
		v := dailybalancegrant.DefaultSource
		_c.mutation.SetSource(v)
	}
	if _, ok := _c.mutation.GrantedAt(); !ok {
		v := dailybalancegrant.DefaultGrantedAt()
		_c.mutation.SetGrantedAt(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := dailybalancegrant.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *DailyBalanceGrantCreate) check() error {
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "DailyBalanceGrant.user_id"`)}
	}
	if _, ok := _c.mutation.GroupID(); !ok {
		return &ValidationError{Name: "group_id", err: errors.New(`ent: missing required field "DailyBalanceGrant.group_id"`)}
	}
	if _, ok := _c.mutation.Amount(); !ok {
		return &ValidationError{Name: "amount", err: errors.New(`ent: missing required field "DailyBalanceGrant.amount"`)}
	}
	if _, ok := _c.mutation.Remaining(); !ok {
		return &ValidationError{Name: "remaining", err: errors.New(`ent: missing required field "DailyBalanceGrant.remaining"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "DailyBalanceGrant.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := dailybalancegrant.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "DailyBalanceGrant.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Source(); !ok {
		return &ValidationError{Name: "source", err: errors.New(`ent: missing required field "DailyBalanceGrant.source"`)}
	}
	if v, ok := _c.mutation.Source(); ok {
		if err := dailybalancegrant.SourceValidator(v); err != nil {
			return &ValidationError{Name: "source", err: fmt.Errorf(`ent: validator failed for field "DailyBalanceGrant.source": %w`, err)}
		}
	}
	if _, ok := _c.mutation.GrantedAt(); !ok {
		return &ValidationError{Name: "granted_at", err: errors.New(`ent: missing required field "DailyBalanceGrant.granted_at"`)}
	}
	if _, ok := _c.mutation.ExpiresAt(); !ok {
		return &ValidationError{Name: "expires_at", err: errors.New(`ent: missing required field "DailyBalanceGrant.expires_at"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "DailyBalanceGrant.created_at"`)}
	}
	return nil
}

func (_c *DailyBalanceGrantCreate) sqlSave(ctx context.Context) (*DailyBalanceGrant, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *DailyBalanceGrantCreate) createSpec() (*DailyBalanceGrant, *sqlgraph.CreateSpec) {
	var (
		_node = &DailyBalanceGrant{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(dailybalancegrant.Table, sqlgraph.NewFieldSpec(dailybalancegrant.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(dailybalancegrant.FieldUserID, field.TypeInt64, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.GroupID(); ok {
		_spec.SetField(dailybalancegrant.FieldGroupID, field.TypeInt64, value)
		_node.GroupID = value
	}
	if value, ok := _c.mutation.Amount(); ok {
		_spec.SetField(dailybalancegrant.FieldAmount, field.TypeFloat64, value)
		_node.Amount = value
	}
	if value, ok := _c.mutation.Remaining(); ok {
		_spec.SetField(dailybalancegrant.FieldRemaining, field.TypeFloat64, value)
		_node.Remaining = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(dailybalancegrant.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.Source(); ok {
		_spec.SetField(dailybalancegrant.FieldSource, field.TypeString, value)
		_node.Source = value
	}
	if value, ok := _c.mutation.SourceRef(); ok {
		_spec.SetField(dailybalancegrant.FieldSourceRef, field.TypeString, value)
		_node.SourceRef = &value
	}
	if value, ok := _c.mutation.GrantedAt(); ok {
		_spec.SetField(dailybalancegrant.FieldGrantedAt, field.TypeTime, value)
		_node.GrantedAt = value
	}
	if value, ok := _c.mutation.ExpiresAt(); ok {
		_spec.SetField(dailybalancegrant.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(dailybalancegrant.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.DailyBalanceGrant.Create().
//		SetUserID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.DailyBalanceGrantUpsert) {
//			SetUserID(v+v).
//		}).
//		Exec(ctx)
func (_c *DailyBalanceGrantCreate) OnConflict(opts ...sql.ConflictOption) *DailyBalanceGrantUpsertOne {
	_c.conflict = opts
	return &DailyBalanceGrantUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.DailyBalanceGrant.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *DailyBalanceGrantCreate) OnConflictColumns(columns ...string) *DailyBalanceGrantUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &DailyBalanceGrantUpsertOne{
		create: _c,
	}
}

type (
	// DailyBalanceGrantUpsertOne is the builder for "upsert"-ing
	//  one DailyBalanceGrant node.
	DailyBalanceGrantUpsertOne struct {
		create *DailyBalanceGrantCreate
	}

	// DailyBalanceGrantUpsert is the "OnConflict" setter.
	DailyBalanceGrantUpsert struct {
		*sql.UpdateSet
	}
)

// SetUserID sets the "user_id" field.
func (u *DailyBalanceGrantUpsert) SetUserID(v int64) *DailyBalanceGrantUpsert {
	u.Set(dailybalancegrant.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *DailyBalanceGrantUpsert) UpdateUserID() *DailyBalanceGrantUpsert {
	u.SetExcluded(dailybalancegrant.FieldUserID)
	return u
}

// AddUserID adds v to the "user_id" field.
func (u *DailyBalanceGrantUpsert) AddUserID(v int64) *DailyBalanceGrantUpsert {
	u.Add(dailybalancegrant.FieldUserID, v)
	return u
}

// SetGroupID sets the "group_id" field.
func (u *DailyBalanceGrantUpsert) SetGroupID(v int64) *DailyBalanceGrantUpsert {
	u.Set(dailybalancegrant.FieldGroupID, v)
	return u
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *DailyBalanceGrantUpsert) UpdateGroupID() *DailyBalanceGrantUpsert {
	u.SetExcluded(dailybalancegrant.FieldGroupID)
	return u
}

// AddGroupID adds v to the "group_id" field.
func (u *DailyBalanceGrantUpsert) AddGroupID(v int64) *DailyBalanceGrantUpsert {
	u.Add(dailybalancegrant.FieldGroupID, v)
	return u
}

// SetAmount sets the "amount" field.
func (u *DailyBalanceGrantUpsert) SetAmount(v float64) *DailyBalanceGrantUpsert {
	u.Set(dailybalancegrant.FieldAmount, v)
	return u
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *DailyBalanceGrantUpsert) UpdateAmount() *DailyBalanceGrantUpsert {
	u.SetExcluded(dailybalancegrant.FieldAmount)
	return u
}

// AddAmount adds v to the "amount" field.
func (u *DailyBalanceGrantUpsert) AddAmount(v float64) *DailyBalanceGrantUpsert {
	u.Add(dailybalancegrant.FieldAmount, v)
	return u
}

// SetRemaining sets the "remaining" field.
func (u *DailyBalanceGrantUpsert) SetRemaining(v float64) *DailyBalanceGrantUpsert {
	u.Set(dailybalancegrant.FieldRemaining, v)
	return u
}

// UpdateRemaining sets the "remaining" field to the value that was provided on create.
func (u *DailyBalanceGrantUpsert) UpdateRemaining() *DailyBalanceGrantUpsert {
	u.SetExcluded(dailybalancegrant.FieldRemaining)
	return u
}

// AddRemaining adds v to the "remaining" field.
func (u *DailyBalanceGrantUpsert) AddRemaining(v float64) *DailyBalanceGrantUpsert {
	u.Add(dailybalancegrant.FieldRemaining, v)
	return u
}

// SetStatus sets the "status" field.
func (u *DailyBalanceGrantUpsert) SetStatus(v string) *DailyBalanceGrantUpsert {
	u.Set(dailybalancegrant.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *DailyBalanceGrantUpsert) UpdateStatus() *DailyBalanceGrantUpsert {
	u.SetExcluded(dailybalancegrant.FieldStatus)
	return u
}

// SetSource sets the "source" field.
func (u *DailyBalanceGrantUpsert) SetSource(v string) *DailyBalanceGrantUpsert {
	u.Set(dailybalancegrant.FieldSource, v)
	return u
}

// UpdateSource sets the "source" field to the value that was provided on create.
func (u *DailyBalanceGrantUpsert) UpdateSource() *DailyBalanceGrantUpsert {
	u.SetExcluded(dailybalancegrant.FieldSource)
	return u
}

// SetSourceRef sets the "source_ref" field.
func (u *DailyBalanceGrantUpsert) SetSourceRef(v string) *DailyBalanceGrantUpsert {
	u.Set(dailybalancegrant.FieldSourceRef, v)
	return u
}

// UpdateSourceRef sets the "source_ref" field to the value that was provided on create.
func (u *DailyBalanceGrantUpsert) UpdateSourceRef() *DailyBalanceGrantUpsert {
	u.SetExcluded(dailybalancegrant.FieldSourceRef)
	return u
}

// ClearSourceRef clears the value of the "source_ref" field.
func (u *DailyBalanceGrantUpsert) ClearSourceRef() *DailyBalanceGrantUpsert {
	u.SetNull(dailybalancegrant.FieldSourceRef)
	return u
}

// SetGrantedAt sets the "granted_at" field.
func (u *DailyBalanceGrantUpsert) SetGrantedAt(v time.Time) *DailyBalanceGrantUpsert {
	u.Set(dailybalancegrant.FieldGrantedAt, v)
	return u
}

// UpdateGrantedAt sets the "granted_at" field to the value that was provided on create.
func (u *DailyBalanceGrantUpsert) UpdateGrantedAt() *DailyBalanceGrantUpsert {
	u.SetExcluded(dailybalancegrant.FieldGrantedAt)
	return u
}

// SetExpiresAt sets the "expires_at" field.
func (u *DailyBalanceGrantUpsert) SetExpiresAt(v time.Time) *DailyBalanceGrantUpsert {
	u.Set(dailybalancegrant.FieldExpiresAt, v)
	return u
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *DailyBalanceGrantUpsert) UpdateExpiresAt() *DailyBalanceGrantUpsert {
	u.SetExcluded(dailybalancegrant.FieldExpiresAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.DailyBalanceGrant.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *DailyBalanceGrantUpsertOne) UpdateNewValues() *DailyBalanceGrantUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(dailybalancegrant.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.DailyBalanceGrant.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *DailyBalanceGrantUpsertOne) Ignore() *DailyBalanceGrantUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *DailyBalanceGrantUpsertOne) DoNothing() *DailyBalanceGrantUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the DailyBalanceGrantCreate.OnConflict
// documentation for more info.
func (u *DailyBalanceGrantUpsertOne) Update(set func(*DailyBalanceGrantUpsert)) *DailyBalanceGrantUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&DailyBalanceGrantUpsert{UpdateSet: update})
	}))
	return u
}

// SetUserID sets the "user_id" field.
func (u *DailyBalanceGrantUpsertOne) SetUserID(v int64) *DailyBalanceGrantUpsertOne {
	return u.Update(func(s *DailyBalanceGrantUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *DailyBalanceGrantUpsertOne) AddUserID(v int64) *DailyBalanceGrantUpsertOne {
	return u.Update(func(s *DailyBalanceGrantUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *DailyBalanceGrantUpsertOne) UpdateUserID() *DailyBalanceGrantUpsertOne {
	return u.Update(func(s *DailyBalanceGrantUpsert) {
		s.UpdateUserID()
	})
}

// SetGroupID sets the "group_id" field.
func (u *DailyBalanceGrantUpsertOne) SetGroupID(v int64) *DailyBalanceGrantUpsertOne {
	return u.Update(func(s *DailyBalanceGrantUpsert) {
		s.SetGroupID(v)
	})
}

// AddGroupID adds v to the "group_id" field.
func (u *DailyBalanceGrantUpsertOne) AddGroupID(v int64) *DailyBalanceGrantUpsertOne {
	return u.Update(func(s *DailyBalanceGrantUpsert) {
		s.AddGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *DailyBalanceGrantUpsertOne) UpdateGroupID() *DailyBalanceGrantUpsertOne {
	return u.Update(func(s *DailyBalanceGrantUpsert) {
		s.UpdateGroupID()
	})
}

// SetAmount sets the "amount" field.
func (u *DailyBalanceGrantUpsertOne) SetAmount(v float64) *DailyBalanceGrantUpsertOne {
	return u.Update(func(s *DailyBalanceGrantUpsert) {
		s.SetAmount(v)
	})
}

// AddAmount adds v to the "amount" field.
func (u *DailyBalanceGrantUpsertOne) AddAmount(v float64) *DailyBalanceGrantUpsertOne {
	return u.Update(func(s *DailyBalanceGrantUpsert) {
		s.AddAmount(v)
	})
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *DailyBalanceGrantUpsertOne) UpdateAmount() *DailyBalanceGrantUpsertOne {
	return u.Update(func(s *DailyBalanceGrantUpsert) {
		s.UpdateAmount()
	})
}

// SetRemaining sets the "remaining" field.
func (u *DailyBalanceGrantUpsertOne) SetRemaining(v float64) *DailyBalanceGrantUpsertOne {
	return u.Update(func(s *DailyBalanceGrantUpsert) {
		s.SetRemaining(v)
	})
}

// AddRemaining adds v to the "remaining" field.
func (u *DailyBalanceGrantUpsertOne) AddRemaining(v float64) *DailyBalanceGrantUpsertOne {
	return u.Update(func(s *DailyBalanceGrantUpsert) {
		s.AddRemaining(v)
	})
}

// UpdateRemaining sets the "remaining" field to the value that was provided on create.
func (u *DailyBalanceGrantUpsertOne) UpdateRemaining() *DailyBalanceGrantUpsertOne {
	return u.Update(func(s *DailyBalanceGrantUpsert) {
		s.UpdateRemaining()
	})
}

// SetStatus sets the "status" field.
func (u *DailyBalanceGrantUpsertOne) SetStatus(v string) *DailyBalanceGrantUpsertOne {
	return u.Update(func(s *DailyBalanceGrantUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *DailyBalanceGrantUpsertOne) UpdateStatus() *DailyBalanceGrantUpsertOne {
	return u.Update(func(s *DailyBalanceGrantUpsert) {
		s.UpdateStatus()
	})
}

// SetSource sets the "source" field.
func (u *DailyBalanceGrantUpsertOne) SetSource(v string) *DailyBalanceGrantUpsertOne {
	return u.Update(func(s *DailyBalanceGrantUpsert) {
		s.SetSource(v)
	})
}

// UpdateSource sets the "source" field to the value that was provided on create.
func (u *DailyBalanceGrantUpsertOne) UpdateSource() *DailyBalanceGrantUpsertOne {
	return u.Update(func(s *DailyBalanceGrantUpsert) {
		s.UpdateSource()
	})
}

// SetSourceRef sets the "source_ref" field.
func (u *DailyBalanceGrantUpsertOne) SetSourceRef(v string) *DailyBalanceGrantUpsertOne {
	return u.Update(func(s *DailyBalanceGrantUpsert) {
		s.SetSourceRef(v)
	})
}

// UpdateSourceRef sets the "source_ref" field to the value that was provided on create.
func (u *DailyBalanceGrantUpsertOne) UpdateSourceRef() *DailyBalanceGrantUpsertOne {
	return u.Update(func(s *DailyBalanceGrantUpsert) {
		s.UpdateSourceRef()
	})
}

// ClearSourceRef clears the value of the "source_ref" field.
func (u *DailyBalanceGrantUpsertOne) ClearSourceRef() *DailyBalanceGrantUpsertOne {
	return u.Update(func(s *DailyBalanceGrantUpsert) {
		s.ClearSourceRef()
	})
}

// SetGrantedAt sets the "granted_at" field.
func (u *DailyBalanceGrantUpsertOne) SetGrantedAt(v time.Time) *DailyBalanceGrantUpsertOne {
	return u.Update(func(s *DailyBalanceGrantUpsert) {
		s.SetGrantedAt(v)
	})
}

// UpdateGrantedAt sets the "granted_at" field to the value that was provided on create.
func (u *DailyBalanceGrantUpsertOne) UpdateGrantedAt() *DailyBalanceGrantUpsertOne {
	return u.Update(func(s *DailyBalanceGrantUpsert) {
		s.UpdateGrantedAt()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *DailyBalanceGrantUpsertOne) SetExpiresAt(v time.Time) *DailyBalanceGrantUpsertOne {
	return u.Update(func(s *DailyBalanceGrantUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *DailyBalanceGrantUpsertOne) UpdateExpiresAt() *DailyBalanceGrantUpsertOne {
	return u.Update(func(s *DailyBalanceGrantUpsert) {
		s.UpdateExpiresAt()
	})
}

// Exec executes the query.
func (u *DailyBalanceGrantUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for DailyBalanceGrantCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *DailyBalanceGrantUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *DailyBalanceGrantUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *DailyBalanceGrantUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// DailyBalanceGrantCreateBulk is the builder for creating many DailyBalanceGrant entities in bulk.
type DailyBalanceGrantCreateBulk struct {
	config
	err      error
	builders []*DailyBalanceGrantCreate
	conflict []sql.ConflictOption
}

// Save creates the DailyBalanceGrant entities in the database.
func (_c *DailyBalanceGrantCreateBulk) Save(ctx context.Context) ([]*DailyBalanceGrant, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*DailyBalanceGrant, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*DailyBalanceGrantMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *DailyBalanceGrantCreateBulk) SaveX(ctx context.Context) []*DailyBalanceGrant {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DailyBalanceGrantCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DailyBalanceGrantCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.DailyBalanceGrant.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.DailyBalanceGrantUpsert) {
//			SetUserID(v+v).
//		}).
//		Exec(ctx)
func (_c *DailyBalanceGrantCreateBulk) OnConflict(opts ...sql.ConflictOption) *DailyBalanceGrantUpsertBulk {
	_c.conflict = opts
	return &DailyBalanceGrantUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.DailyBalanceGrant.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *DailyBalanceGrantCreateBulk) OnConflictColumns(columns ...string) *DailyBalanceGrantUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &DailyBalanceGrantUpsertBulk{
		create: _c,
	}
}

// DailyBalanceGrantUpsertBulk is the builder for "upsert"-ing
// a bulk of DailyBalanceGrant nodes.
type DailyBalanceGrantUpsertBulk struct {
	create *DailyBalanceGrantCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.DailyBalanceGrant.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *DailyBalanceGrantUpsertBulk) UpdateNewValues() *DailyBalanceGrantUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(dailybalancegrant.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.DailyBalanceGrant.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *DailyBalanceGrantUpsertBulk) Ignore() *DailyBalanceGrantUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *DailyBalanceGrantUpsertBulk) DoNothing() *DailyBalanceGrantUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the DailyBalanceGrantCreateBulk.OnConflict
// documentation for more info.
func (u *DailyBalanceGrantUpsertBulk) Update(set func(*DailyBalanceGrantUpsert)) *DailyBalanceGrantUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&DailyBalanceGrantUpsert{UpdateSet: update})
	}))
	return u
}

// SetUserID sets the "user_id" field.
func (u *DailyBalanceGrantUpsertBulk) SetUserID(v int64) *DailyBalanceGrantUpsertBulk {
	return u.Update(func(s *DailyBalanceGrantUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *DailyBalanceGrantUpsertBulk) AddUserID(v int64) *DailyBalanceGrantUpsertBulk {
	return u.Update(func(s *DailyBalanceGrantUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *DailyBalanceGrantUpsertBulk) UpdateUserID() *DailyBalanceGrantUpsertBulk {
	return u.Update(func(s *DailyBalanceGrantUpsert) {
		s.UpdateUserID()
	})
}

// SetGroupID sets the "group_id" field.
func (u *DailyBalanceGrantUpsertBulk) SetGroupID(v int64) *DailyBalanceGrantUpsertBulk {
	return u.Update(func(s *DailyBalanceGrantUpsert) {
		s.SetGroupID(v)
	})
}

// AddGroupID adds v to the "group_id" field.
func (u *DailyBalanceGrantUpsertBulk) AddGroupID(v int64) *DailyBalanceGrantUpsertBulk {
	return u.Update(func(s *DailyBalanceGrantUpsert) {
		s.AddGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *DailyBalanceGrantUpsertBulk) UpdateGroupID() *DailyBalanceGrantUpsertBulk {
	return u.Update(func(s *DailyBalanceGrantUpsert) {
		s.UpdateGroupID()
	})
}

// SetAmount sets the "amount" field.
func (u *DailyBalanceGrantUpsertBulk) SetAmount(v float64) *DailyBalanceGrantUpsertBulk {
	return u.Update(func(s *DailyBalanceGrantUpsert) {
		s.SetAmount(v)
	})
}

// AddAmount adds v to the "amount" field.
func (u *DailyBalanceGrantUpsertBulk) AddAmount(v float64) *DailyBalanceGrantUpsertBulk {
	return u.Update(func(s *DailyBalanceGrantUpsert) {
		s.AddAmount(v)
	})
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *DailyBalanceGrantUpsertBulk) UpdateAmount() *DailyBalanceGrantUpsertBulk {
	return u.Update(func(s *DailyBalanceGrantUpsert) {
		s.UpdateAmount()
	})
}

// SetRemaining sets the "remaining" field.
func (u *DailyBalanceGrantUpsertBulk) SetRemaining(v float64) *DailyBalanceGrantUpsertBulk {
	return u.Update(func(s *DailyBalanceGrantUpsert) {
		s.SetRemaining(v)
	})
}

// AddRemaining adds v to the "remaining" field.
func (u *DailyBalanceGrantUpsertBulk) AddRemaining(v float64) *DailyBalanceGrantUpsertBulk {
	return u.Update(func(s *DailyBalanceGrantUpsert) {
		s.AddRemaining(v)
	})
}

// UpdateRemaining sets the "remaining" field to the value that was provided on create.
func (u *DailyBalanceGrantUpsertBulk) UpdateRemaining() *DailyBalanceGrantUpsertBulk {
	return u.Update(func(s *DailyBalanceGrantUpsert) {
		s.UpdateRemaining()
	})
}

// SetStatus sets the "status" field.
func (u *DailyBalanceGrantUpsertBulk) SetStatus(v string) *DailyBalanceGrantUpsertBulk {
	return u.Update(func(s *DailyBalanceGrantUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *DailyBalanceGrantUpsertBulk) UpdateStatus() *DailyBalanceGrantUpsertBulk {
	return u.Update(func(s *DailyBalanceGrantUpsert) {
		s.UpdateStatus()
	})
}

// SetSource sets the "source" field.
func (u *DailyBalanceGrantUpsertBulk) SetSource(v string) *DailyBalanceGrantUpsertBulk {
	return u.Update(func(s *DailyBalanceGrantUpsert) {
		s.SetSource(v)
	})
}

// UpdateSource sets the "source" field to the value that was provided on create.
func (u *DailyBalanceGrantUpsertBulk) UpdateSource() *DailyBalanceGrantUpsertBulk {
	return u.Update(func(s *DailyBalanceGrantUpsert) {
		s.UpdateSource()
	})
}

// SetSourceRef sets the "source_ref" field.
func (u *DailyBalanceGrantUpsertBulk) SetSourceRef(v string) *DailyBalanceGrantUpsertBulk {
	return u.Update(func(s *DailyBalanceGrantUpsert) {
		s.SetSourceRef(v)
	})
}

// UpdateSourceRef sets the "source_ref" field to the value that was provided on create.
func (u *DailyBalanceGrantUpsertBulk) UpdateSourceRef() *DailyBalanceGrantUpsertBulk {
	return u.Update(func(s *DailyBalanceGrantUpsert) {
		s.UpdateSourceRef()
	})
}

// ClearSourceRef clears the value of the "source_ref" field.
func (u *DailyBalanceGrantUpsertBulk) ClearSourceRef() *DailyBalanceGrantUpsertBulk {
	return u.Update(func(s *DailyBalanceGrantUpsert) {
		s.ClearSourceRef()
	})
}

// SetGrantedAt sets the "granted_at" field.
func (u *DailyBalanceGrantUpsertBulk) SetGrantedAt(v time.Time) *DailyBalanceGrantUpsertBulk {
	return u.Update(func(s *DailyBalanceGrantUpsert) {
		s.SetGrantedAt(v)
	})
}

// UpdateGrantedAt sets the "granted_at" field to the value that was provided on create.
func (u *DailyBalanceGrantUpsertBulk) UpdateGrantedAt() *DailyBalanceGrantUpsertBulk {
	return u.Update(func(s *DailyBalanceGrantUpsert) {
		s.UpdateGrantedAt()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *DailyBalanceGrantUpsertBulk) SetExpiresAt(v time.Time) *DailyBalanceGrantUpsertBulk {
	return u.Update(func(s *DailyBalanceGrantUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *DailyBalanceGrantUpsertBulk) UpdateExpiresAt() *DailyBalanceGrantUpsertBulk {
	return u.Update(func(s *DailyBalanceGrantUpsert) {
		s.UpdateExpiresAt()
	})
}

// Exec executes the query.
func (u *DailyBalanceGrantUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the DailyBalanceGrantCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for DailyBalanceGrantCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *DailyBalanceGrantUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
