// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/subscriptionpurchaseclaim"
)

// SubscriptionPurchaseClaimQuery is the builder for querying SubscriptionPurchaseClaim entities.
type SubscriptionPurchaseClaimQuery struct {
	config
	ctx        *QueryContext
	order      []subscriptionpurchaseclaim.OrderOption
	inters     []Interceptor
	predicates []predicate.SubscriptionPurchaseClaim
	modifiers  []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the SubscriptionPurchaseClaimQuery builder.
func (_q *SubscriptionPurchaseClaimQuery) Where(ps ...predicate.SubscriptionPurchaseClaim) *SubscriptionPurchaseClaimQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *SubscriptionPurchaseClaimQuery) Limit(limit int) *SubscriptionPurchaseClaimQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *SubscriptionPurchaseClaimQuery) Offset(offset int) *SubscriptionPurchaseClaimQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *SubscriptionPurchaseClaimQuery) Unique(unique bool) *SubscriptionPurchaseClaimQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *SubscriptionPurchaseClaimQuery) Order(o ...subscriptionpurchaseclaim.OrderOption) *SubscriptionPurchaseClaimQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// First returns the first SubscriptionPurchaseClaim entity from the query.
// Returns a *NotFoundError when no SubscriptionPurchaseClaim was found.
func (_q *SubscriptionPurchaseClaimQuery) First(ctx context.Context) (*SubscriptionPurchaseClaim, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{subscriptionpurchaseclaim.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *SubscriptionPurchaseClaimQuery) FirstX(ctx context.Context) *SubscriptionPurchaseClaim {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first SubscriptionPurchaseClaim ID from the query.
// Returns a *NotFoundError when no SubscriptionPurchaseClaim ID was found.
func (_q *SubscriptionPurchaseClaimQuery) FirstID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{subscriptionpurchaseclaim.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *SubscriptionPurchaseClaimQuery) FirstIDX(ctx context.Context) int64 {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single SubscriptionPurchaseClaim entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one SubscriptionPurchaseClaim entity is found.
// Returns a *NotFoundError when no SubscriptionPurchaseClaim entities are found.
func (_q *SubscriptionPurchaseClaimQuery) Only(ctx context.Context) (*SubscriptionPurchaseClaim, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{subscriptionpurchaseclaim.Label}
	default:
		return nil, &NotSingularError{subscriptionpurchaseclaim.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *SubscriptionPurchaseClaimQuery) OnlyX(ctx context.Context) *SubscriptionPurchaseClaim {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only SubscriptionPurchaseClaim ID in the query.
// Returns a *NotSingularError when more than one SubscriptionPurchaseClaim ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *SubscriptionPurchaseClaimQuery) OnlyID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{subscriptionpurchaseclaim.Label}
	default:
		err = &NotSingularError{subscriptionpurchaseclaim.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *SubscriptionPurchaseClaimQuery) OnlyIDX(ctx context.Context) int64 {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of SubscriptionPurchaseClaims.
func (_q *SubscriptionPurchaseClaimQuery) All(ctx context.Context) ([]*SubscriptionPurchaseClaim, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*SubscriptionPurchaseClaim, *SubscriptionPurchaseClaimQuery]()
	return withInterceptors[[]*SubscriptionPurchaseClaim](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *SubscriptionPurchaseClaimQuery) AllX(ctx context.Context) []*SubscriptionPurchaseClaim {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of SubscriptionPurchaseClaim IDs.
func (_q *SubscriptionPurchaseClaimQuery) IDs(ctx context.Context) (ids []int64, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(subscriptionpurchaseclaim.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *SubscriptionPurchaseClaimQuery) IDsX(ctx context.Context) []int64 {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *SubscriptionPurchaseClaimQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*SubscriptionPurchaseClaimQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *SubscriptionPurchaseClaimQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *SubscriptionPurchaseClaimQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *SubscriptionPurchaseClaimQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the SubscriptionPurchaseClaimQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *SubscriptionPurchaseClaimQuery) Clone() *SubscriptionPurchaseClaimQuery {
	if _q == nil {
		return nil
	}
	return &SubscriptionPurchaseClaimQuery{
		config:     _q.config,
		ctx:        _q.ctx.Clone(),
		order:      append([]subscriptionpurchaseclaim.OrderOption{}, _q.order...),
		inters:     append([]Interceptor{}, _q.inters...),
		predicates: append([]predicate.SubscriptionPurchaseClaim{}, _q.predicates...),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		UserID int64 `json:"user_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.SubscriptionPurchaseClaim.Query().
//		GroupBy(subscriptionpurchaseclaim.FieldUserID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *SubscriptionPurchaseClaimQuery) GroupBy(field string, fields ...string) *SubscriptionPurchaseClaimGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &SubscriptionPurchaseClaimGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = subscriptionpurchaseclaim.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		UserID int64 `json:"user_id,omitempty"`
//	}
//
//	client.SubscriptionPurchaseClaim.Query().
//		Select(subscriptionpurchaseclaim.FieldUserID).
//		Scan(ctx, &v)
func (_q *SubscriptionPurchaseClaimQuery) Select(fields ...string) *SubscriptionPurchaseClaimSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &SubscriptionPurchaseClaimSelect{SubscriptionPurchaseClaimQuery: _q}
	sbuild.label = subscriptionpurchaseclaim.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a SubscriptionPurchaseClaimSelect configured with the given aggregations.
func (_q *SubscriptionPurchaseClaimQuery) Aggregate(fns ...AggregateFunc) *SubscriptionPurchaseClaimSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *SubscriptionPurchaseClaimQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !subscriptionpurchaseclaim.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *SubscriptionPurchaseClaimQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*SubscriptionPurchaseClaim, error) {
	var (
		nodes = []*SubscriptionPurchaseClaim{}
		_spec = _q.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*SubscriptionPurchaseClaim).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &SubscriptionPurchaseClaim{config: _q.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (_q *SubscriptionPurchaseClaimQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *SubscriptionPurchaseClaimQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(subscriptionpurchaseclaim.Table, subscriptionpurchaseclaim.Columns, sqlgraph.NewFieldSpec(subscriptionpurchaseclaim.FieldID, field.TypeInt64))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, subscriptionpurchaseclaim.FieldID)
		for i := range fields {
			if fields[i] != subscriptionpurchaseclaim.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *SubscriptionPurchaseClaimQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(subscriptionpurchaseclaim.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = subscriptionpurchaseclaim.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range _q.modifiers {
		m(selector)
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ForUpdate locks the selected rows against concurrent updates, and prevent them from being
// updated, deleted or "selected ... for update" by other sessions, until the transaction is
// either committed or rolled-back.
func (_q *SubscriptionPurchaseClaimQuery) ForUpdate(opts ...sql.LockOption) *SubscriptionPurchaseClaimQuery {
	if _q.driver.Dialect() == dialect.Postgres {
		_q.Unique(false)
	}
	_q.modifiers = append(_q.modifiers, func(s *sql.Selector) {
		s.ForUpdate(opts...)
	})
	return _q
}

// ForShare behaves similarly to ForUpdate, except that it acquires a shared mode lock
// on any rows that are read. Other sessions can read the rows, but cannot modify them
// until your transaction commits.
func (_q *SubscriptionPurchaseClaimQuery) ForShare(opts ...sql.LockOption) *SubscriptionPurchaseClaimQuery {
	if _q.driver.Dialect() == dialect.Postgres {
		_q.Unique(false)
	}
	_q.modifiers = append(_q.modifiers, func(s *sql.Selector) {
		s.ForShare(opts...)
	})
	return _q
}

// SubscriptionPurchaseClaimGroupBy is the group-by builder for SubscriptionPurchaseClaim entities.
type SubscriptionPurchaseClaimGroupBy struct {
	selector
	build *SubscriptionPurchaseClaimQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *SubscriptionPurchaseClaimGroupBy) Aggregate(fns ...AggregateFunc) *SubscriptionPurchaseClaimGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *SubscriptionPurchaseClaimGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*SubscriptionPurchaseClaimQuery, *SubscriptionPurchaseClaimGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *SubscriptionPurchaseClaimGroupBy) sqlScan(ctx context.Context, root *SubscriptionPurchaseClaimQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// SubscriptionPurchaseClaimSelect is the builder for selecting fields of SubscriptionPurchaseClaim entities.
type SubscriptionPurchaseClaimSelect struct {
	*SubscriptionPurchaseClaimQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *SubscriptionPurchaseClaimSelect) Aggregate(fns ...AggregateFunc) *SubscriptionPurchaseClaimSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *SubscriptionPurchaseClaimSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*SubscriptionPurchaseClaimQuery, *SubscriptionPurchaseClaimSelect](ctx, _s.SubscriptionPurchaseClaimQuery, _s, _s.inters, v)
}

func (_s *SubscriptionPurchaseClaimSelect) sqlScan(ctx context.Context, root *SubscriptionPurchaseClaimQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
