// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/subscriptionpurchaseclaim"
)

// SubscriptionPurchaseClaimCreate is the builder for creating a SubscriptionPurchaseClaim entity.
type SubscriptionPurchaseClaimCreate struct {
	config
	mutation *SubscriptionPurchaseClaimMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetUserID sets the "user_id" field.
func (_c *SubscriptionPurchaseClaimCreate) SetUserID(v int64) *SubscriptionPurchaseClaimCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetSubscriptionGroupID sets the "subscription_group_id" field.
func (_c *SubscriptionPurchaseClaimCreate) SetSubscriptionGroupID(v int64) *SubscriptionPurchaseClaimCreate {
	_c.mutation.SetSubscriptionGroupID(v)
	return _c
}

// SetPaymentOrderID sets the "payment_order_id" field.
func (_c *SubscriptionPurchaseClaimCreate) SetPaymentOrderID(v int64) *SubscriptionPurchaseClaimCreate {
	_c.mutation.SetPaymentOrderID(v)
	return _c
}

// SetNillablePaymentOrderID sets the "payment_order_id" field if the given value is not nil.
func (_c *SubscriptionPurchaseClaimCreate) SetNillablePaymentOrderID(v *int64) *SubscriptionPurchaseClaimCreate {
	if v != nil {
		_c.SetPaymentOrderID(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *SubscriptionPurchaseClaimCreate) SetStatus(v string) *SubscriptionPurchaseClaimCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *SubscriptionPurchaseClaimCreate) SetNillableStatus(v *string) *SubscriptionPurchaseClaimCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *SubscriptionPurchaseClaimCreate) SetCreatedAt(v time.Time) *SubscriptionPurchaseClaimCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *SubscriptionPurchaseClaimCreate) SetNillableCreatedAt(v *time.Time) *SubscriptionPurchaseClaimCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *SubscriptionPurchaseClaimCreate) SetUpdatedAt(v time.Time) *SubscriptionPurchaseClaimCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *SubscriptionPurchaseClaimCreate) SetNillableUpdatedAt(v *time.Time) *SubscriptionPurchaseClaimCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// Mutation returns the SubscriptionPurchaseClaimMutation object of the builder.
func (_c *SubscriptionPurchaseClaimCreate) Mutation() *SubscriptionPurchaseClaimMutation {
	return _c.mutation
}

// Save creates the SubscriptionPurchaseClaim in the database.
func (_c *SubscriptionPurchaseClaimCreate) Save(ctx context.Context) (*SubscriptionPurchaseClaim, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SubscriptionPurchaseClaimCreate) SaveX(ctx context.Context) *SubscriptionPurchaseClaim {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SubscriptionPurchaseClaimCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SubscriptionPurchaseClaimCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *SubscriptionPurchaseClaimCreate) defaults() {
	if _, ok := _c.mutation.Status(); !ok {
		v := subscriptionpurchaseclaim.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := subscriptionpurchaseclaim.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := subscriptionpurchaseclaim.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *SubscriptionPurchaseClaimCreate) check() error {
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "SubscriptionPurchaseClaim.user_id"`)}
	}
	if _, ok := _c.mutation.SubscriptionGroupID(); !ok {
		return &ValidationError{Name: "subscription_group_id", err: errors.New(`ent: missing required field "SubscriptionPurchaseClaim.subscription_group_id"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "SubscriptionPurchaseClaim.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := subscriptionpurchaseclaim.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "SubscriptionPurchaseClaim.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "SubscriptionPurchaseClaim.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "SubscriptionPurchaseClaim.updated_at"`)}
	}
	return nil
}

func (_c *SubscriptionPurchaseClaimCreate) sqlSave(ctx context.Context) (*SubscriptionPurchaseClaim, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SubscriptionPurchaseClaimCreate) createSpec() (*SubscriptionPurchaseClaim, *sqlgraph.CreateSpec) {
	var (
		_node = &SubscriptionPurchaseClaim{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(subscriptionpurchaseclaim.Table, sqlgraph.NewFieldSpec(subscriptionpurchaseclaim.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(subscriptionpurchaseclaim.FieldUserID, field.TypeInt64, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.SubscriptionGroupID(); ok {
		_spec.SetField(subscriptionpurchaseclaim.FieldSubscriptionGroupID, field.TypeInt64, value)
		_node.SubscriptionGroupID = value
	}
	if value, ok := _c.mutation.PaymentOrderID(); ok {
		_spec.SetField(subscriptionpurchaseclaim.FieldPaymentOrderID, field.TypeInt64, value)
		_node.PaymentOrderID = &value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(subscriptionpurchaseclaim.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(subscriptionpurchaseclaim.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(subscriptionpurchaseclaim.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.SubscriptionPurchaseClaim.Create().
//		SetUserID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SubscriptionPurchaseClaimUpsert) {
//			SetUserID(v+v).
//		}).
//		Exec(ctx)
func (_c *SubscriptionPurchaseClaimCreate) OnConflict(opts ...sql.ConflictOption) *SubscriptionPurchaseClaimUpsertOne {
	_c.conflict = opts
	return &SubscriptionPurchaseClaimUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.SubscriptionPurchaseClaim.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SubscriptionPurchaseClaimCreate) OnConflictColumns(columns ...string) *SubscriptionPurchaseClaimUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SubscriptionPurchaseClaimUpsertOne{
		create: _c,
	}
}

type (
	// SubscriptionPurchaseClaimUpsertOne is the builder for "upsert"-ing
	//  one SubscriptionPurchaseClaim node.
	SubscriptionPurchaseClaimUpsertOne struct {
		create *SubscriptionPurchaseClaimCreate
	}

	// SubscriptionPurchaseClaimUpsert is the "OnConflict" setter.
	SubscriptionPurchaseClaimUpsert struct {
		*sql.UpdateSet
	}
)

// SetUserID sets the "user_id" field.
func (u *SubscriptionPurchaseClaimUpsert) SetUserID(v int64) *SubscriptionPurchaseClaimUpsert {
	u.Set(subscriptionpurchaseclaim.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *SubscriptionPurchaseClaimUpsert) UpdateUserID() *SubscriptionPurchaseClaimUpsert {
	u.SetExcluded(subscriptionpurchaseclaim.FieldUserID)
	return u
}

// AddUserID adds v to the "user_id" field.
func (u *SubscriptionPurchaseClaimUpsert) AddUserID(v int64) *SubscriptionPurchaseClaimUpsert {
	u.Add(subscriptionpurchaseclaim.FieldUserID, v)
	return u
}

// SetSubscriptionGroupID sets the "subscription_group_id" field.
func (u *SubscriptionPurchaseClaimUpsert) SetSubscriptionGroupID(v int64) *SubscriptionPurchaseClaimUpsert {
	u.Set(subscriptionpurchaseclaim.FieldSubscriptionGroupID, v)
	return u
}

// UpdateSubscriptionGroupID sets the "subscription_group_id" field to the value that was provided on create.
func (u *SubscriptionPurchaseClaimUpsert) UpdateSubscriptionGroupID() *SubscriptionPurchaseClaimUpsert {
	u.SetExcluded(subscriptionpurchaseclaim.FieldSubscriptionGroupID)
	return u
}

// AddSubscriptionGroupID adds v to the "subscription_group_id" field.
func (u *SubscriptionPurchaseClaimUpsert) AddSubscriptionGroupID(v int64) *SubscriptionPurchaseClaimUpsert {
	u.Add(subscriptionpurchaseclaim.FieldSubscriptionGroupID, v)
	return u
}

// SetPaymentOrderID sets the "payment_order_id" field.
func (u *SubscriptionPurchaseClaimUpsert) SetPaymentOrderID(v int64) *SubscriptionPurchaseClaimUpsert {
	u.Set(subscriptionpurchaseclaim.FieldPaymentOrderID, v)
	return u
}

// UpdatePaymentOrderID sets the "payment_order_id" field to the value that was provided on create.
func (u *SubscriptionPurchaseClaimUpsert) UpdatePaymentOrderID() *SubscriptionPurchaseClaimUpsert {
	u.SetExcluded(subscriptionpurchaseclaim.FieldPaymentOrderID)
	return u
}

// AddPaymentOrderID adds v to the "payment_order_id" field.
func (u *SubscriptionPurchaseClaimUpsert) AddPaymentOrderID(v int64) *SubscriptionPurchaseClaimUpsert {
	u.Add(subscriptionpurchaseclaim.FieldPaymentOrderID, v)
	return u
}

// ClearPaymentOrderID clears the value of the "payment_order_id" field.
func (u *SubscriptionPurchaseClaimUpsert) ClearPaymentOrderID() *SubscriptionPurchaseClaimUpsert {
	u.SetNull(subscriptionpurchaseclaim.FieldPaymentOrderID)
	return u
}

// SetStatus sets the "status" field.
func (u *SubscriptionPurchaseClaimUpsert) SetStatus(v string) *SubscriptionPurchaseClaimUpsert {
	u.Set(subscriptionpurchaseclaim.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *SubscriptionPurchaseClaimUpsert) UpdateStatus() *SubscriptionPurchaseClaimUpsert {
	u.SetExcluded(subscriptionpurchaseclaim.FieldStatus)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *SubscriptionPurchaseClaimUpsert) SetUpdatedAt(v time.Time) *SubscriptionPurchaseClaimUpsert {
	u.Set(subscriptionpurchaseclaim.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *SubscriptionPurchaseClaimUpsert) UpdateUpdatedAt() *SubscriptionPurchaseClaimUpsert {
	u.SetExcluded(subscriptionpurchaseclaim.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.SubscriptionPurchaseClaim.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *SubscriptionPurchaseClaimUpsertOne) UpdateNewValues() *SubscriptionPurchaseClaimUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(subscriptionpurchaseclaim.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.SubscriptionPurchaseClaim.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *SubscriptionPurchaseClaimUpsertOne) Ignore() *SubscriptionPurchaseClaimUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SubscriptionPurchaseClaimUpsertOne) DoNothing() *SubscriptionPurchaseClaimUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SubscriptionPurchaseClaimCreate.OnConflict
// documentation for more info.
func (u *SubscriptionPurchaseClaimUpsertOne) Update(set func(*SubscriptionPurchaseClaimUpsert)) *SubscriptionPurchaseClaimUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SubscriptionPurchaseClaimUpsert{UpdateSet: update})
	}))
	return u
}

// SetUserID sets the "user_id" field.
func (u *SubscriptionPurchaseClaimUpsertOne) SetUserID(v int64) *SubscriptionPurchaseClaimUpsertOne {
	return u.Update(func(s *SubscriptionPurchaseClaimUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *SubscriptionPurchaseClaimUpsertOne) AddUserID(v int64) *SubscriptionPurchaseClaimUpsertOne {
	return u.Update(func(s *SubscriptionPurchaseClaimUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *SubscriptionPurchaseClaimUpsertOne) UpdateUserID() *SubscriptionPurchaseClaimUpsertOne {
	return u.Update(func(s *SubscriptionPurchaseClaimUpsert) {
		s.UpdateUserID()
	})
}

// SetSubscriptionGroupID sets the "subscription_group_id" field.
func (u *SubscriptionPurchaseClaimUpsertOne) SetSubscriptionGroupID(v int64) *SubscriptionPurchaseClaimUpsertOne {
	return u.Update(func(s *SubscriptionPurchaseClaimUpsert) {
		s.SetSubscriptionGroupID(v)
	})
}

// AddSubscriptionGroupID adds v to the "subscription_group_id" field.
func (u *SubscriptionPurchaseClaimUpsertOne) AddSubscriptionGroupID(v int64) *SubscriptionPurchaseClaimUpsertOne {
	return u.Update(func(s *SubscriptionPurchaseClaimUpsert) {
		s.AddSubscriptionGroupID(v)
	})
}

// UpdateSubscriptionGroupID sets the "subscription_group_id" field to the value that was provided on create.
func (u *SubscriptionPurchaseClaimUpsertOne) UpdateSubscriptionGroupID() *SubscriptionPurchaseClaimUpsertOne {
	return u.Update(func(s *SubscriptionPurchaseClaimUpsert) {
		s.UpdateSubscriptionGroupID()
	})
}

// SetPaymentOrderID sets the "payment_order_id" field.
func (u *SubscriptionPurchaseClaimUpsertOne) SetPaymentOrderID(v int64) *SubscriptionPurchaseClaimUpsertOne {
	return u.Update(func(s *SubscriptionPurchaseClaimUpsert) {
		s.SetPaymentOrderID(v)
	})
}

// AddPaymentOrderID adds v to the "payment_order_id" field.
func (u *SubscriptionPurchaseClaimUpsertOne) AddPaymentOrderID(v int64) *SubscriptionPurchaseClaimUpsertOne {
	return u.Update(func(s *SubscriptionPurchaseClaimUpsert) {
		s.AddPaymentOrderID(v)
	})
}

// UpdatePaymentOrderID sets the "payment_order_id" field to the value that was provided on create.
func (u *SubscriptionPurchaseClaimUpsertOne) UpdatePaymentOrderID() *SubscriptionPurchaseClaimUpsertOne {
	return u.Update(func(s *SubscriptionPurchaseClaimUpsert) {
		s.UpdatePaymentOrderID()
	})
}

// ClearPaymentOrderID clears the value of the "payment_order_id" field.
func (u *SubscriptionPurchaseClaimUpsertOne) ClearPaymentOrderID() *SubscriptionPurchaseClaimUpsertOne {
	return u.Update(func(s *SubscriptionPurchaseClaimUpsert) {
		s.ClearPaymentOrderID()
	})
}

// SetStatus sets the "status" field.
func (u *SubscriptionPurchaseClaimUpsertOne) SetStatus(v string) *SubscriptionPurchaseClaimUpsertOne {
	return u.Update(func(s *SubscriptionPurchaseClaimUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *SubscriptionPurchaseClaimUpsertOne) UpdateStatus() *SubscriptionPurchaseClaimUpsertOne {
	return u.Update(func(s *SubscriptionPurchaseClaimUpsert) {
		s.UpdateStatus()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *SubscriptionPurchaseClaimUpsertOne) SetUpdatedAt(v time.Time) *SubscriptionPurchaseClaimUpsertOne {
	return u.Update(func(s *SubscriptionPurchaseClaimUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *SubscriptionPurchaseClaimUpsertOne) UpdateUpdatedAt() *SubscriptionPurchaseClaimUpsertOne {
	return u.Update(func(s *SubscriptionPurchaseClaimUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *SubscriptionPurchaseClaimUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SubscriptionPurchaseClaimCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SubscriptionPurchaseClaimUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *SubscriptionPurchaseClaimUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *SubscriptionPurchaseClaimUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// SubscriptionPurchaseClaimCreateBulk is the builder for creating many SubscriptionPurchaseClaim entities in bulk.
type SubscriptionPurchaseClaimCreateBulk struct {
	config
	err      error
	builders []*SubscriptionPurchaseClaimCreate
	conflict []sql.ConflictOption
}

// Save creates the SubscriptionPurchaseClaim entities in the database.
func (_c *SubscriptionPurchaseClaimCreateBulk) Save(ctx context.Context) ([]*SubscriptionPurchaseClaim, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*SubscriptionPurchaseClaim, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SubscriptionPurchaseClaimMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SubscriptionPurchaseClaimCreateBulk) SaveX(ctx context.Context) []*SubscriptionPurchaseClaim {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SubscriptionPurchaseClaimCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SubscriptionPurchaseClaimCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.SubscriptionPurchaseClaim.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SubscriptionPurchaseClaimUpsert) {
//			SetUserID(v+v).
//		}).
//		Exec(ctx)
func (_c *SubscriptionPurchaseClaimCreateBulk) OnConflict(opts ...sql.ConflictOption) *SubscriptionPurchaseClaimUpsertBulk {
	_c.conflict = opts
	return &SubscriptionPurchaseClaimUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.SubscriptionPurchaseClaim.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SubscriptionPurchaseClaimCreateBulk) OnConflictColumns(columns ...string) *SubscriptionPurchaseClaimUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SubscriptionPurchaseClaimUpsertBulk{
		create: _c,
	}
}

// SubscriptionPurchaseClaimUpsertBulk is the builder for "upsert"-ing
// a bulk of SubscriptionPurchaseClaim nodes.
type SubscriptionPurchaseClaimUpsertBulk struct {
	create *SubscriptionPurchaseClaimCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.SubscriptionPurchaseClaim.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *SubscriptionPurchaseClaimUpsertBulk) UpdateNewValues() *SubscriptionPurchaseClaimUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(subscriptionpurchaseclaim.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.SubscriptionPurchaseClaim.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *SubscriptionPurchaseClaimUpsertBulk) Ignore() *SubscriptionPurchaseClaimUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SubscriptionPurchaseClaimUpsertBulk) DoNothing() *SubscriptionPurchaseClaimUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SubscriptionPurchaseClaimCreateBulk.OnConflict
// documentation for more info.
func (u *SubscriptionPurchaseClaimUpsertBulk) Update(set func(*SubscriptionPurchaseClaimUpsert)) *SubscriptionPurchaseClaimUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SubscriptionPurchaseClaimUpsert{UpdateSet: update})
	}))
	return u
}

// SetUserID sets the "user_id" field.
func (u *SubscriptionPurchaseClaimUpsertBulk) SetUserID(v int64) *SubscriptionPurchaseClaimUpsertBulk {
	return u.Update(func(s *SubscriptionPurchaseClaimUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *SubscriptionPurchaseClaimUpsertBulk) AddUserID(v int64) *SubscriptionPurchaseClaimUpsertBulk {
	return u.Update(func(s *SubscriptionPurchaseClaimUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *SubscriptionPurchaseClaimUpsertBulk) UpdateUserID() *SubscriptionPurchaseClaimUpsertBulk {
	return u.Update(func(s *SubscriptionPurchaseClaimUpsert) {
		s.UpdateUserID()
	})
}

// SetSubscriptionGroupID sets the "subscription_group_id" field.
func (u *SubscriptionPurchaseClaimUpsertBulk) SetSubscriptionGroupID(v int64) *SubscriptionPurchaseClaimUpsertBulk {
	return u.Update(func(s *SubscriptionPurchaseClaimUpsert) {
		s.SetSubscriptionGroupID(v)
	})
}

// AddSubscriptionGroupID adds v to the "subscription_group_id" field.
func (u *SubscriptionPurchaseClaimUpsertBulk) AddSubscriptionGroupID(v int64) *SubscriptionPurchaseClaimUpsertBulk {
	return u.Update(func(s *SubscriptionPurchaseClaimUpsert) {
		s.AddSubscriptionGroupID(v)
	})
}

// UpdateSubscriptionGroupID sets the "subscription_group_id" field to the value that was provided on create.
func (u *SubscriptionPurchaseClaimUpsertBulk) UpdateSubscriptionGroupID() *SubscriptionPurchaseClaimUpsertBulk {
	return u.Update(func(s *SubscriptionPurchaseClaimUpsert) {
		s.UpdateSubscriptionGroupID()
	})
}

// SetPaymentOrderID sets the "payment_order_id" field.
func (u *SubscriptionPurchaseClaimUpsertBulk) SetPaymentOrderID(v int64) *SubscriptionPurchaseClaimUpsertBulk {
	return u.Update(func(s *SubscriptionPurchaseClaimUpsert) {
		s.SetPaymentOrderID(v)
	})
}

// AddPaymentOrderID adds v to the "payment_order_id" field.
func (u *SubscriptionPurchaseClaimUpsertBulk) AddPaymentOrderID(v int64) *SubscriptionPurchaseClaimUpsertBulk {
	return u.Update(func(s *SubscriptionPurchaseClaimUpsert) {
		s.AddPaymentOrderID(v)
	})
}

// UpdatePaymentOrderID sets the "payment_order_id" field to the value that was provided on create.
func (u *SubscriptionPurchaseClaimUpsertBulk) UpdatePaymentOrderID() *SubscriptionPurchaseClaimUpsertBulk {
	return u.Update(func(s *SubscriptionPurchaseClaimUpsert) {
		s.UpdatePaymentOrderID()
	})
}

// ClearPaymentOrderID clears the value of the "payment_order_id" field.
func (u *SubscriptionPurchaseClaimUpsertBulk) ClearPaymentOrderID() *SubscriptionPurchaseClaimUpsertBulk {
	return u.Update(func(s *SubscriptionPurchaseClaimUpsert) {
		s.ClearPaymentOrderID()
	})
}

// SetStatus sets the "status" field.
func (u *SubscriptionPurchaseClaimUpsertBulk) SetStatus(v string) *SubscriptionPurchaseClaimUpsertBulk {
	return u.Update(func(s *SubscriptionPurchaseClaimUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *SubscriptionPurchaseClaimUpsertBulk) UpdateStatus() *SubscriptionPurchaseClaimUpsertBulk {
	return u.Update(func(s *SubscriptionPurchaseClaimUpsert) {
		s.UpdateStatus()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *SubscriptionPurchaseClaimUpsertBulk) SetUpdatedAt(v time.Time) *SubscriptionPurchaseClaimUpsertBulk {
	return u.Update(func(s *SubscriptionPurchaseClaimUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *SubscriptionPurchaseClaimUpsertBulk) UpdateUpdatedAt() *SubscriptionPurchaseClaimUpsertBulk {
	return u.Update(func(s *SubscriptionPurchaseClaimUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *SubscriptionPurchaseClaimUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the SubscriptionPurchaseClaimCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SubscriptionPurchaseClaimCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SubscriptionPurchaseClaimUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
