// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/subscriptionpurchaseclaim"
)

// SubscriptionPurchaseClaimUpdate is the builder for updating SubscriptionPurchaseClaim entities.
type SubscriptionPurchaseClaimUpdate struct {
	config
	hooks    []Hook
	mutation *SubscriptionPurchaseClaimMutation
}

// Where appends a list predicates to the SubscriptionPurchaseClaimUpdate builder.
func (_u *SubscriptionPurchaseClaimUpdate) Where(ps ...predicate.SubscriptionPurchaseClaim) *SubscriptionPurchaseClaimUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *SubscriptionPurchaseClaimUpdate) SetUserID(v int64) *SubscriptionPurchaseClaimUpdate {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *SubscriptionPurchaseClaimUpdate) SetNillableUserID(v *int64) *SubscriptionPurchaseClaimUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *SubscriptionPurchaseClaimUpdate) AddUserID(v int64) *SubscriptionPurchaseClaimUpdate {
	_u.mutation.AddUserID(v)
	return _u
}

// SetSubscriptionGroupID sets the "subscription_group_id" field.
func (_u *SubscriptionPurchaseClaimUpdate) SetSubscriptionGroupID(v int64) *SubscriptionPurchaseClaimUpdate {
	_u.mutation.ResetSubscriptionGroupID()
	_u.mutation.SetSubscriptionGroupID(v)
	return _u
}

// SetNillableSubscriptionGroupID sets the "subscription_group_id" field if the given value is not nil.
func (_u *SubscriptionPurchaseClaimUpdate) SetNillableSubscriptionGroupID(v *int64) *SubscriptionPurchaseClaimUpdate {
	if v != nil {
		_u.SetSubscriptionGroupID(*v)
	}
	return _u
}

// AddSubscriptionGroupID adds value to the "subscription_group_id" field.
func (_u *SubscriptionPurchaseClaimUpdate) AddSubscriptionGroupID(v int64) *SubscriptionPurchaseClaimUpdate {
	_u.mutation.AddSubscriptionGroupID(v)
	return _u
}

// SetPaymentOrderID sets the "payment_order_id" field.
func (_u *SubscriptionPurchaseClaimUpdate) SetPaymentOrderID(v int64) *SubscriptionPurchaseClaimUpdate {
	_u.mutation.ResetPaymentOrderID()
	_u.mutation.SetPaymentOrderID(v)
	return _u
}

// SetNillablePaymentOrderID sets the "payment_order_id" field if the given value is not nil.
func (_u *SubscriptionPurchaseClaimUpdate) SetNillablePaymentOrderID(v *int64) *SubscriptionPurchaseClaimUpdate {
	if v != nil {
		_u.SetPaymentOrderID(*v)
	}
	return _u
}

// AddPaymentOrderID adds value to the "payment_order_id" field.
func (_u *SubscriptionPurchaseClaimUpdate) AddPaymentOrderID(v int64) *SubscriptionPurchaseClaimUpdate {
	_u.mutation.AddPaymentOrderID(v)
	return _u
}

// ClearPaymentOrderID clears the value of the "payment_order_id" field.
func (_u *SubscriptionPurchaseClaimUpdate) ClearPaymentOrderID() *SubscriptionPurchaseClaimUpdate {
	_u.mutation.ClearPaymentOrderID()
	return _u
}

// SetStatus sets the "status" field.
func (_u *SubscriptionPurchaseClaimUpdate) SetStatus(v string) *SubscriptionPurchaseClaimUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *SubscriptionPurchaseClaimUpdate) SetNillableStatus(v *string) *SubscriptionPurchaseClaimUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SubscriptionPurchaseClaimUpdate) SetUpdatedAt(v time.Time) *SubscriptionPurchaseClaimUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the SubscriptionPurchaseClaimMutation object of the builder.
func (_u *SubscriptionPurchaseClaimUpdate) Mutation() *SubscriptionPurchaseClaimMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SubscriptionPurchaseClaimUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SubscriptionPurchaseClaimUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SubscriptionPurchaseClaimUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SubscriptionPurchaseClaimUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SubscriptionPurchaseClaimUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := subscriptionpurchaseclaim.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SubscriptionPurchaseClaimUpdate) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := subscriptionpurchaseclaim.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "SubscriptionPurchaseClaim.status": %w`, err)}
		}
	}
	return nil
}

func (_u *SubscriptionPurchaseClaimUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(subscriptionpurchaseclaim.Table, subscriptionpurchaseclaim.Columns, sqlgraph.NewFieldSpec(subscriptionpurchaseclaim.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(subscriptionpurchaseclaim.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(subscriptionpurchaseclaim.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.SubscriptionGroupID(); ok {
		_spec.SetField(subscriptionpurchaseclaim.FieldSubscriptionGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSubscriptionGroupID(); ok {
		_spec.AddField(subscriptionpurchaseclaim.FieldSubscriptionGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.PaymentOrderID(); ok {
		_spec.SetField(subscriptionpurchaseclaim.FieldPaymentOrderID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedPaymentOrderID(); ok {
		_spec.AddField(subscriptionpurchaseclaim.FieldPaymentOrderID, field.TypeInt64, value)
	}
	if _u.mutation.PaymentOrderIDCleared() {
		_spec.ClearField(subscriptionpurchaseclaim.FieldPaymentOrderID, field.TypeInt64)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(subscriptionpurchaseclaim.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(subscriptionpurchaseclaim.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{subscriptionpurchaseclaim.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SubscriptionPurchaseClaimUpdateOne is the builder for updating a single SubscriptionPurchaseClaim entity.
type SubscriptionPurchaseClaimUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SubscriptionPurchaseClaimMutation
}

// SetUserID sets the "user_id" field.
func (_u *SubscriptionPurchaseClaimUpdateOne) SetUserID(v int64) *SubscriptionPurchaseClaimUpdateOne {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *SubscriptionPurchaseClaimUpdateOne) SetNillableUserID(v *int64) *SubscriptionPurchaseClaimUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *SubscriptionPurchaseClaimUpdateOne) AddUserID(v int64) *SubscriptionPurchaseClaimUpdateOne {
	_u.mutation.AddUserID(v)
	return _u
}

// SetSubscriptionGroupID sets the "subscription_group_id" field.
func (_u *SubscriptionPurchaseClaimUpdateOne) SetSubscriptionGroupID(v int64) *SubscriptionPurchaseClaimUpdateOne {
	_u.mutation.ResetSubscriptionGroupID()
	_u.mutation.SetSubscriptionGroupID(v)
	return _u
}

// SetNillableSubscriptionGroupID sets the "subscription_group_id" field if the given value is not nil.
func (_u *SubscriptionPurchaseClaimUpdateOne) SetNillableSubscriptionGroupID(v *int64) *SubscriptionPurchaseClaimUpdateOne {
	if v != nil {
		_u.SetSubscriptionGroupID(*v)
	}
	return _u
}

// AddSubscriptionGroupID adds value to the "subscription_group_id" field.
func (_u *SubscriptionPurchaseClaimUpdateOne) AddSubscriptionGroupID(v int64) *SubscriptionPurchaseClaimUpdateOne {
	_u.mutation.AddSubscriptionGroupID(v)
	return _u
}

// SetPaymentOrderID sets the "payment_order_id" field.
func (_u *SubscriptionPurchaseClaimUpdateOne) SetPaymentOrderID(v int64) *SubscriptionPurchaseClaimUpdateOne {
	_u.mutation.ResetPaymentOrderID()
	_u.mutation.SetPaymentOrderID(v)
	return _u
}

// SetNillablePaymentOrderID sets the "payment_order_id" field if the given value is not nil.
func (_u *SubscriptionPurchaseClaimUpdateOne) SetNillablePaymentOrderID(v *int64) *SubscriptionPurchaseClaimUpdateOne {
	if v != nil {
		_u.SetPaymentOrderID(*v)
	}
	return _u
}

// AddPaymentOrderID adds value to the "payment_order_id" field.
func (_u *SubscriptionPurchaseClaimUpdateOne) AddPaymentOrderID(v int64) *SubscriptionPurchaseClaimUpdateOne {
	_u.mutation.AddPaymentOrderID(v)
	return _u
}

// ClearPaymentOrderID clears the value of the "payment_order_id" field.
func (_u *SubscriptionPurchaseClaimUpdateOne) ClearPaymentOrderID() *SubscriptionPurchaseClaimUpdateOne {
	_u.mutation.ClearPaymentOrderID()
	return _u
}

// SetStatus sets the "status" field.
func (_u *SubscriptionPurchaseClaimUpdateOne) SetStatus(v string) *SubscriptionPurchaseClaimUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *SubscriptionPurchaseClaimUpdateOne) SetNillableStatus(v *string) *SubscriptionPurchaseClaimUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SubscriptionPurchaseClaimUpdateOne) SetUpdatedAt(v time.Time) *SubscriptionPurchaseClaimUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the SubscriptionPurchaseClaimMutation object of the builder.
func (_u *SubscriptionPurchaseClaimUpdateOne) Mutation() *SubscriptionPurchaseClaimMutation {
	return _u.mutation
}

// Where appends a list predicates to the SubscriptionPurchaseClaimUpdate builder.
func (_u *SubscriptionPurchaseClaimUpdateOne) Where(ps ...predicate.SubscriptionPurchaseClaim) *SubscriptionPurchaseClaimUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SubscriptionPurchaseClaimUpdateOne) Select(field string, fields ...string) *SubscriptionPurchaseClaimUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated SubscriptionPurchaseClaim entity.
func (_u *SubscriptionPurchaseClaimUpdateOne) Save(ctx context.Context) (*SubscriptionPurchaseClaim, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SubscriptionPurchaseClaimUpdateOne) SaveX(ctx context.Context) *SubscriptionPurchaseClaim {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SubscriptionPurchaseClaimUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SubscriptionPurchaseClaimUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SubscriptionPurchaseClaimUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := subscriptionpurchaseclaim.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SubscriptionPurchaseClaimUpdateOne) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := subscriptionpurchaseclaim.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "SubscriptionPurchaseClaim.status": %w`, err)}
		}
	}
	return nil
}

func (_u *SubscriptionPurchaseClaimUpdateOne) sqlSave(ctx context.Context) (_node *SubscriptionPurchaseClaim, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(subscriptionpurchaseclaim.Table, subscriptionpurchaseclaim.Columns, sqlgraph.NewFieldSpec(subscriptionpurchaseclaim.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "SubscriptionPurchaseClaim.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, subscriptionpurchaseclaim.FieldID)
		for _, f := range fields {
			if !subscriptionpurchaseclaim.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != subscriptionpurchaseclaim.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(subscriptionpurchaseclaim.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(subscriptionpurchaseclaim.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.SubscriptionGroupID(); ok {
		_spec.SetField(subscriptionpurchaseclaim.FieldSubscriptionGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSubscriptionGroupID(); ok {
		_spec.AddField(subscriptionpurchaseclaim.FieldSubscriptionGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.PaymentOrderID(); ok {
		_spec.SetField(subscriptionpurchaseclaim.FieldPaymentOrderID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedPaymentOrderID(); ok {
		_spec.AddField(subscriptionpurchaseclaim.FieldPaymentOrderID, field.TypeInt64, value)
	}
	if _u.mutation.PaymentOrderIDCleared() {
		_spec.ClearField(subscriptionpurchaseclaim.FieldPaymentOrderID, field.TypeInt64)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(subscriptionpurchaseclaim.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(subscriptionpurchaseclaim.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &SubscriptionPurchaseClaim{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{subscriptionpurchaseclaim.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
