// Code generated by ent, DO NOT EDIT.

package dailybalancegrant

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.DailyBalanceGrant {
	return predicate.DailyBalanceGrant(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.DailyBalanceGrant {
	return predicate.DailyBalanceGrant(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.DailyBalanceGrant {
	return predicate.DailyBalanceGrant(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.DailyBalanceGrant {
	return predicate.DailyBalanceGrant(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.DailyBalanceGrant {
	return predicate.DailyBalanceGrant(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.DailyBalanceGrant {
	return predicate.DailyBalanceGrant(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.DailyBalanceGrant {
	return predicate.DailyBalanceGrant(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.DailyBalanceGrant {
	return predicate.DailyBalanceGrant(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.DailyBalanceGrant {
	return predicate.DailyBalanceGrant(sql.FieldLTE(FieldID, id))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.DailyBalanceGrant {
	return predicate.DailyBalanceGrant(sql.FieldEQ(FieldUserID, v))
}

// GroupID applies equality check predicate on the "group_id" field. It's identical to GroupIDEQ.
func GroupID(v int64) predicate.DailyBalanceGrant {
	return predicate.DailyBalanceGrant(sql.FieldEQ(FieldGroupID, v))
}

// Amount applies equality check predicate on the "amount" field. It's identical to AmountEQ.
func Amount(v float64) predicate.DailyBalanceGrant {
	return predicate.DailyBalanceGrant(sql.FieldEQ(FieldAmount, v))
}

// Remaining applies equality check predicate on the "remaining" field. It's identical to RemainingEQ.
func Remaining(v float64) predicate.DailyBalanceGrant {
	return predicate.DailyBalanceGrant(sql.FieldEQ(FieldRemaining, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.DailyBalanceGrant {
	return predicate.DailyBalanceGrant(sql.FieldEQ(FieldStatus, v))
}

// Source applies equality check predicate on the "source" field. It's identical to SourceEQ.
func Source(v string) predicate.DailyBalanceGrant {
	return predicate.DailyBalanceGrant(sql.FieldEQ(FieldSource, v))
}

// SourceRef applies equality check predicate on the "source_ref" field. It's identical to SourceRefEQ.
func SourceRef(v string) predicate.DailyBalanceGrant {
	return predicate.DailyBalanceGrant(sql.FieldEQ(FieldSourceRef, v))
}

// GrantedAt applies equality check predicate on the "granted_at" field. It's identical to GrantedAtEQ.
func GrantedAt(v time.Time) predicate.DailyBalanceGrant {
	return predicate.DailyBalanceGrant(sql.FieldEQ(FieldGrantedAt, v))
}

// ExpiresAt applies equality check predicate on the "expires_at" field. It's identical to ExpiresAtEQ.
func ExpiresAt(v time.Time) predicate.DailyBalanceGrant {
	return predicate.DailyBalanceGrant(sql.FieldEQ(FieldExpiresAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.DailyBalanceGrant {
	return predicate.DailyBalanceGrant(sql.FieldEQ(FieldCreatedAt, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.DailyBalanceGrant {
	return predicate.DailyBalanceGrant(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.DailyBalanceGrant {
	return predicate.DailyBalanceGrant(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.DailyBalanceGrant {
	return predicate.DailyBalanceGrant(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.DailyBalanceGrant {
	return predicate.DailyBalanceGrant(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v int64) predicate.DailyBalanceGrant {
	return predicate.DailyBalanceGrant(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v int64) predicate.DailyBalanceGrant {
	return predicate.DailyBalanceGrant(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v int64) predicate.DailyBalanceGrant {
	return predicate.DailyBalanceGrant(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v int64) predicate.DailyBalanceGrant {
	return predicate.DailyBalanceGrant(sql.FieldLTE(FieldUserID, v))
}

// GroupIDEQ applies the EQ predicate on the "group_id" field.
func GroupIDEQ(v int64) predicate.DailyBalanceGrant {
	return predicate.DailyBalanceGrant(sql.FieldEQ(FieldGroupID, v))
}

// GroupIDNEQ applies the NEQ predicate on the "group_id" field.
func GroupIDNEQ(v int64) predicate.DailyBalanceGrant {
	return predicate.DailyBalanceGrant(sql.FieldNEQ(FieldGroupID, v))
}

// GroupIDIn applies the In predicate on the "group_id" field.
func GroupIDIn(vs ...int64) predicate.DailyBalanceGrant {
	return predicate.DailyBalanceGrant(sql.FieldIn(FieldGroupID, vs...))
}

// GroupIDNotIn applies the NotIn predicate on the "group_id" field.
func GroupIDNotIn(vs ...int64) predicate.DailyBalanceGrant {
	return predicate.DailyBalanceGrant(sql.FieldNotIn(FieldGroupID, vs...))
}

// GroupIDGT applies the GT predicate on the "group_id" field.
func GroupIDGT(v int64) predicate.DailyBalanceGrant {
	return predicate.DailyBalanceGrant(sql.FieldGT(FieldGroupID, v))
}

// GroupIDGTE applies the GTE predicate on the "group_id" field.
func GroupIDGTE(v int64) predicate.DailyBalanceGrant {
	return predicate.DailyBalanceGrant(sql.FieldGTE(FieldGroupID, v))
}

// GroupIDLT applies the LT predicate on the "group_id" field.
func GroupIDLT(v int64) predicate.DailyBalanceGrant {
	return predicate.DailyBalanceGrant(sql.FieldLT(FieldGroupID, v))
}

// GroupIDLTE applies the LTE predicate on the "group_id" field.
func GroupIDLTE(v int64) predicate.DailyBalanceGrant {
	return predicate.DailyBalanceGrant(sql.FieldLTE(FieldGroupID, v))
}

// AmountEQ applies the EQ predicate on the "amount" field.
func AmountEQ(v float64) predicate.DailyBalanceGrant {
	return predicate.DailyBalanceGrant(sql.FieldEQ(FieldAmount, v))
}

// AmountNEQ applies the NEQ predicate on the "amount" field.
func AmountNEQ(v float64) predicate.DailyBalanceGrant {
	return predicate.DailyBalanceGrant(sql.FieldNEQ(FieldAmount, v))
}

// AmountIn applies the In predicate on the "amount" field.
func AmountIn(vs ...float64) predicate.DailyBalanceGrant {
	return predicate.DailyBalanceGrant(sql.FieldIn(FieldAmount, vs...))
}

// AmountNotIn applies the NotIn predicate on the "amount" field.
func AmountNotIn(vs ...float64) predicate.DailyBalanceGrant {
	return predicate.DailyBalanceGrant(sql.FieldNotIn(FieldAmount, vs...))
}

// AmountGT applies the GT predicate on the "amount" field.
func AmountGT(v float64) predicate.DailyBalanceGrant {
	return predicate.DailyBalanceGrant(sql.FieldGT(FieldAmount, v))
}

// AmountGTE applies the GTE predicate on the "amount" field.
func AmountGTE(v float64) predicate.DailyBalanceGrant {
	return predicate.DailyBalanceGrant(sql.FieldGTE(FieldAmount, v))
}

// AmountLT applies the LT predicate on the "amount" field.
func AmountLT(v float64) predicate.DailyBalanceGrant {
	return predicate.DailyBalanceGrant(sql.FieldLT(FieldAmount, v))
}

// AmountLTE applies the LTE predicate on the "amount" field.
func AmountLTE(v float64) predicate.DailyBalanceGrant {
	return predicate.DailyBalanceGrant(sql.FieldLTE(FieldAmount, v))
}

// RemainingEQ applies the EQ predicate on the "remaining" field.
func RemainingEQ(v float64) predicate.DailyBalanceGrant {
	return predicate.DailyBalanceGrant(sql.FieldEQ(FieldRemaining, v))
}

// RemainingNEQ applies the NEQ predicate on the "remaining" field.
func RemainingNEQ(v float64) predicate.DailyBalanceGrant {
	return predicate.DailyBalanceGrant(sql.FieldNEQ(FieldRemaining, v))
}

// RemainingIn applies the In predicate on the "remaining" field.
func RemainingIn(vs ...float64) predicate.DailyBalanceGrant {
	return predicate.DailyBalanceGrant(sql.FieldIn(FieldRemaining, vs...))
}

// RemainingNotIn applies the NotIn predicate on the "remaining" field.
func RemainingNotIn(vs ...float64) predicate.DailyBalanceGrant {
	return predicate.DailyBalanceGrant(sql.FieldNotIn(FieldRemaining, vs...))
}

// RemainingGT applies the GT predicate on the "remaining" field.
func RemainingGT(v float64) predicate.DailyBalanceGrant {
	return predicate.DailyBalanceGrant(sql.FieldGT(FieldRemaining, v))
}

// RemainingGTE applies the GTE predicate on the "remaining" field.
func RemainingGTE(v float64) predicate.DailyBalanceGrant {
	return predicate.DailyBalanceGrant(sql.FieldGTE(FieldRemaining, v))
}

// RemainingLT applies the LT predicate on the "remaining" field.
func RemainingLT(v float64) predicate.DailyBalanceGrant {
	return predicate.DailyBalanceGrant(sql.FieldLT(FieldRemaining, v))
}

// RemainingLTE applies the LTE predicate on the "remaining" field.
func RemainingLTE(v float64) predicate.DailyBalanceGrant {
	return predicate.DailyBalanceGrant(sql.FieldLTE(FieldRemaining, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.DailyBalanceGrant {
	return predicate.DailyBalanceGrant(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.DailyBalanceGrant {
	return predicate.DailyBalanceGrant(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.DailyBalanceGrant {
	return predicate.DailyBalanceGrant(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.DailyBalanceGrant {
	return predicate.DailyBalanceGrant(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.DailyBalanceGrant {
	return predicate.DailyBalanceGrant(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.DailyBalanceGrant {
	return predicate.DailyBalanceGrant(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.DailyBalanceGrant {
	return predicate.DailyBalanceGrant(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.DailyBalanceGrant {
	return predicate.DailyBalanceGrant(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.DailyBalanceGrant {
	return predicate.DailyBalanceGrant(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.DailyBalanceGrant {
	return predicate.DailyBalanceGrant(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.DailyBalanceGrant {
	return predicate.DailyBalanceGrant(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.DailyBalanceGrant {
	return predicate.DailyBalanceGrant(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.DailyBalanceGrant {
	return predicate.DailyBalanceGrant(sql.FieldContainsFold(FieldStatus, v))
}

// SourceEQ applies the EQ predicate on the "source" field.
func SourceEQ(v string) predicate.DailyBalanceGrant {
	return predicate.DailyBalanceGrant(sql.FieldEQ(FieldSource, v))
}

// SourceNEQ applies the NEQ predicate on the "source" field.
func SourceNEQ(v string) predicate.DailyBalanceGrant {
	return predicate.DailyBalanceGrant(sql.FieldNEQ(FieldSource, v))
}

// SourceIn applies the In predicate on the "source" field.
func SourceIn(vs ...string) predicate.DailyBalanceGrant {
	return predicate.DailyBalanceGrant(sql.FieldIn(FieldSource, vs...))
}

// SourceNotIn applies the NotIn predicate on the "source" field.
func SourceNotIn(vs ...string) predicate.DailyBalanceGrant {
	return predicate.DailyBalanceGrant(sql.FieldNotIn(FieldSource, vs...))
}

// SourceGT applies the GT predicate on the "source" field.
func SourceGT(v string) predicate.DailyBalanceGrant {
	return predicate.DailyBalanceGrant(sql.FieldGT(FieldSource, v))
}

// SourceGTE applies the GTE predicate on the "source" field.
func SourceGTE(v string) predicate.DailyBalanceGrant {
	return predicate.DailyBalanceGrant(sql.FieldGTE(FieldSource, v))
}

// SourceLT applies the LT predicate on the "source" field.
func SourceLT(v string) predicate.DailyBalanceGrant {
	return predicate.DailyBalanceGrant(sql.FieldLT(FieldSource, v))
}

// SourceLTE applies the LTE predicate on the "source" field.
func SourceLTE(v string) predicate.DailyBalanceGrant {
	return predicate.DailyBalanceGrant(sql.FieldLTE(FieldSource, v))
}

// SourceContains applies the Contains predicate on the "source" field.
func SourceContains(v string) predicate.DailyBalanceGrant {
	return predicate.DailyBalanceGrant(sql.FieldContains(FieldSource, v))
}

// SourceHasPrefix applies the HasPrefix predicate on the "source" field.
func SourceHasPrefix(v string) predicate.DailyBalanceGrant {
	return predicate.DailyBalanceGrant(sql.FieldHasPrefix(FieldSource, v))
}

// SourceHasSuffix applies the HasSuffix predicate on the "source" field.
func SourceHasSuffix(v string) predicate.DailyBalanceGrant {
	return predicate.DailyBalanceGrant(sql.FieldHasSuffix(FieldSource, v))
}

// SourceEqualFold applies the EqualFold predicate on the "source" field.
func SourceEqualFold(v string) predicate.DailyBalanceGrant {
	return predicate.DailyBalanceGrant(sql.FieldEqualFold(FieldSource, v))
}

// SourceContainsFold applies the ContainsFold predicate on the "source" field.
func SourceContainsFold(v string) predicate.DailyBalanceGrant {
	return predicate.DailyBalanceGrant(sql.FieldContainsFold(FieldSource, v))
}

// SourceRefEQ applies the EQ predicate on the "source_ref" field.
func SourceRefEQ(v string) predicate.DailyBalanceGrant {
	return predicate.DailyBalanceGrant(sql.FieldEQ(FieldSourceRef, v))
}

// SourceRefNEQ applies the NEQ predicate on the "source_ref" field.
func SourceRefNEQ(v string) predicate.DailyBalanceGrant {
	return predicate.DailyBalanceGrant(sql.FieldNEQ(FieldSourceRef, v))
}

// SourceRefIn applies the In predicate on the "source_ref" field.
func SourceRefIn(vs ...string) predicate.DailyBalanceGrant {
	return predicate.DailyBalanceGrant(sql.FieldIn(FieldSourceRef, vs...))
}

// SourceRefNotIn applies the NotIn predicate on the "source_ref" field.
func SourceRefNotIn(vs ...string) predicate.DailyBalanceGrant {
	return predicate.DailyBalanceGrant(sql.FieldNotIn(FieldSourceRef, vs...))
}

// SourceRefGT applies the GT predicate on the "source_ref" field.
func SourceRefGT(v string) predicate.DailyBalanceGrant {
	return predicate.DailyBalanceGrant(sql.FieldGT(FieldSourceRef, v))
}

// SourceRefGTE applies the GTE predicate on the "source_ref" field.
func SourceRefGTE(v string) predicate.DailyBalanceGrant {
	return predicate.DailyBalanceGrant(sql.FieldGTE(FieldSourceRef, v))
}

// SourceRefLT applies the LT predicate on the "source_ref" field.
func SourceRefLT(v string) predicate.DailyBalanceGrant {
	return predicate.DailyBalanceGrant(sql.FieldLT(FieldSourceRef, v))
}

// SourceRefLTE applies the LTE predicate on the "source_ref" field.
func SourceRefLTE(v string) predicate.DailyBalanceGrant {
	return predicate.DailyBalanceGrant(sql.FieldLTE(FieldSourceRef, v))
}

// SourceRefContains applies the Contains predicate on the "source_ref" field.
func SourceRefContains(v string) predicate.DailyBalanceGrant {
	return predicate.DailyBalanceGrant(sql.FieldContains(FieldSourceRef, v))
}

// SourceRefHasPrefix applies the HasPrefix predicate on the "source_ref" field.
func SourceRefHasPrefix(v string) predicate.DailyBalanceGrant {
	return predicate.DailyBalanceGrant(sql.FieldHasPrefix(FieldSourceRef, v))
}

// SourceRefHasSuffix applies the HasSuffix predicate on the "source_ref" field.
func SourceRefHasSuffix(v string) predicate.DailyBalanceGrant {
	return predicate.DailyBalanceGrant(sql.FieldHasSuffix(FieldSourceRef, v))
}

// SourceRefIsNil applies the IsNil predicate on the "source_ref" field.
func SourceRefIsNil() predicate.DailyBalanceGrant {
	return predicate.DailyBalanceGrant(sql.FieldIsNull(FieldSourceRef))
}

// SourceRefNotNil applies the NotNil predicate on the "source_ref" field.
func SourceRefNotNil() predicate.DailyBalanceGrant {
	return predicate.DailyBalanceGrant(sql.FieldNotNull(FieldSourceRef))
}

// SourceRefEqualFold applies the EqualFold predicate on the "source_ref" field.
func SourceRefEqualFold(v string) predicate.DailyBalanceGrant {
	return predicate.DailyBalanceGrant(sql.FieldEqualFold(FieldSourceRef, v))
}

// SourceRefContainsFold applies the ContainsFold predicate on the "source_ref" field.
func SourceRefContainsFold(v string) predicate.DailyBalanceGrant {
	return predicate.DailyBalanceGrant(sql.FieldContainsFold(FieldSourceRef, v))
}

// GrantedAtEQ applies the EQ predicate on the "granted_at" field.
func GrantedAtEQ(v time.Time) predicate.DailyBalanceGrant {
	return predicate.DailyBalanceGrant(sql.FieldEQ(FieldGrantedAt, v))
}

// GrantedAtNEQ applies the NEQ predicate on the "granted_at" field.
func GrantedAtNEQ(v time.Time) predicate.DailyBalanceGrant {
	return predicate.DailyBalanceGrant(sql.FieldNEQ(FieldGrantedAt, v))
}

// GrantedAtIn applies the In predicate on the "granted_at" field.
func GrantedAtIn(vs ...time.Time) predicate.DailyBalanceGrant {
	return predicate.DailyBalanceGrant(sql.FieldIn(FieldGrantedAt, vs...))
}

// GrantedAtNotIn applies the NotIn predicate on the "granted_at" field.
func GrantedAtNotIn(vs ...time.Time) predicate.DailyBalanceGrant {
	return predicate.DailyBalanceGrant(sql.FieldNotIn(FieldGrantedAt, vs...))
}

// GrantedAtGT applies the GT predicate on the "granted_at" field.
func GrantedAtGT(v time.Time) predicate.DailyBalanceGrant {
	return predicate.DailyBalanceGrant(sql.FieldGT(FieldGrantedAt, v))
}

// GrantedAtGTE applies the GTE predicate on the "granted_at" field.
func GrantedAtGTE(v time.Time) predicate.DailyBalanceGrant {
	return predicate.DailyBalanceGrant(sql.FieldGTE(FieldGrantedAt, v))
}

// GrantedAtLT applies the LT predicate on the "granted_at" field.
func GrantedAtLT(v time.Time) predicate.DailyBalanceGrant {
	return predicate.DailyBalanceGrant(sql.FieldLT(FieldGrantedAt, v))
}

// GrantedAtLTE applies the LTE predicate on the "granted_at" field.
func GrantedAtLTE(v time.Time) predicate.DailyBalanceGrant {
	return predicate.DailyBalanceGrant(sql.FieldLTE(FieldGrantedAt, v))
}

// ExpiresAtEQ applies the EQ predicate on the "expires_at" field.
func ExpiresAtEQ(v time.Time) predicate.DailyBalanceGrant {
	return predicate.DailyBalanceGrant(sql.FieldEQ(FieldExpiresAt, v))
}

// ExpiresAtNEQ applies the NEQ predicate on the "expires_at" field.
func ExpiresAtNEQ(v time.Time) predicate.DailyBalanceGrant {
	return predicate.DailyBalanceGrant(sql.FieldNEQ(FieldExpiresAt, v))
}

// ExpiresAtIn applies the In predicate on the "expires_at" field.
func ExpiresAtIn(vs ...time.Time) predicate.DailyBalanceGrant {
	return predicate.DailyBalanceGrant(sql.FieldIn(FieldExpiresAt, vs...))
}

// ExpiresAtNotIn applies the NotIn predicate on the "expires_at" field.
func ExpiresAtNotIn(vs ...time.Time) predicate.DailyBalanceGrant {
	return predicate.DailyBalanceGrant(sql.FieldNotIn(FieldExpiresAt, vs...))
}

// ExpiresAtGT applies the GT predicate on the "expires_at" field.
func ExpiresAtGT(v time.Time) predicate.DailyBalanceGrant {
	return predicate.DailyBalanceGrant(sql.FieldGT(FieldExpiresAt, v))
}

// ExpiresAtGTE applies the GTE predicate on the "expires_at" field.
func ExpiresAtGTE(v time.Time) predicate.DailyBalanceGrant {
	return predicate.DailyBalanceGrant(sql.FieldGTE(FieldExpiresAt, v))
}

// ExpiresAtLT applies the LT predicate on the "expires_at" field.
func ExpiresAtLT(v time.Time) predicate.DailyBalanceGrant {
	return predicate.DailyBalanceGrant(sql.FieldLT(FieldExpiresAt, v))
}

// ExpiresAtLTE applies the LTE predicate on the "expires_at" field.
func ExpiresAtLTE(v time.Time) predicate.DailyBalanceGrant {
	return predicate.DailyBalanceGrant(sql.FieldLTE(FieldExpiresAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.DailyBalanceGrant {
	return predicate.DailyBalanceGrant(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.DailyBalanceGrant {
	return predicate.DailyBalanceGrant(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.DailyBalanceGrant {
	return predicate.DailyBalanceGrant(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.DailyBalanceGrant {
	return predicate.DailyBalanceGrant(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.DailyBalanceGrant {
	return predicate.DailyBalanceGrant(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.DailyBalanceGrant {
	return predicate.DailyBalanceGrant(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.DailyBalanceGrant {
	return predicate.DailyBalanceGrant(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.DailyBalanceGrant {
	return predicate.DailyBalanceGrant(sql.FieldLTE(FieldCreatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.DailyBalanceGrant) predicate.DailyBalanceGrant {
	return predicate.DailyBalanceGrant(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.DailyBalanceGrant) predicate.DailyBalanceGrant {
	return predicate.DailyBalanceGrant(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.DailyBalanceGrant) predicate.DailyBalanceGrant {
	return predicate.DailyBalanceGrant(sql.NotPredicates(p))
}
