// Code generated by ent, DO NOT EDIT.

package subscriptionpurchaseclaim

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.SubscriptionPurchaseClaim {
	return predicate.SubscriptionPurchaseClaim(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.SubscriptionPurchaseClaim {
	return predicate.SubscriptionPurchaseClaim(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.SubscriptionPurchaseClaim {
	return predicate.SubscriptionPurchaseClaim(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.SubscriptionPurchaseClaim {
	return predicate.SubscriptionPurchaseClaim(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.SubscriptionPurchaseClaim {
	return predicate.SubscriptionPurchaseClaim(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.SubscriptionPurchaseClaim {
	return predicate.SubscriptionPurchaseClaim(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.SubscriptionPurchaseClaim {
	return predicate.SubscriptionPurchaseClaim(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.SubscriptionPurchaseClaim {
	return predicate.SubscriptionPurchaseClaim(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.SubscriptionPurchaseClaim {
	return predicate.SubscriptionPurchaseClaim(sql.FieldLTE(FieldID, id))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.SubscriptionPurchaseClaim {
	return predicate.SubscriptionPurchaseClaim(sql.FieldEQ(FieldUserID, v))
}

// SubscriptionGroupID applies equality check predicate on the "subscription_group_id" field. It's identical to SubscriptionGroupIDEQ.
func SubscriptionGroupID(v int64) predicate.SubscriptionPurchaseClaim {
	return predicate.SubscriptionPurchaseClaim(sql.FieldEQ(FieldSubscriptionGroupID, v))
}

// PaymentOrderID applies equality check predicate on the "payment_order_id" field. It's identical to PaymentOrderIDEQ.
func PaymentOrderID(v int64) predicate.SubscriptionPurchaseClaim {
	return predicate.SubscriptionPurchaseClaim(sql.FieldEQ(FieldPaymentOrderID, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.SubscriptionPurchaseClaim {
	return predicate.SubscriptionPurchaseClaim(sql.FieldEQ(FieldStatus, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.SubscriptionPurchaseClaim {
	return predicate.SubscriptionPurchaseClaim(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.SubscriptionPurchaseClaim {
	return predicate.SubscriptionPurchaseClaim(sql.FieldEQ(FieldUpdatedAt, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.SubscriptionPurchaseClaim {
	return predicate.SubscriptionPurchaseClaim(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.SubscriptionPurchaseClaim {
	return predicate.SubscriptionPurchaseClaim(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.SubscriptionPurchaseClaim {
	return predicate.SubscriptionPurchaseClaim(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.SubscriptionPurchaseClaim {
	return predicate.SubscriptionPurchaseClaim(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v int64) predicate.SubscriptionPurchaseClaim {
	return predicate.SubscriptionPurchaseClaim(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v int64) predicate.SubscriptionPurchaseClaim {
	return predicate.SubscriptionPurchaseClaim(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v int64) predicate.SubscriptionPurchaseClaim {
	return predicate.SubscriptionPurchaseClaim(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v int64) predicate.SubscriptionPurchaseClaim {
	return predicate.SubscriptionPurchaseClaim(sql.FieldLTE(FieldUserID, v))
}

// SubscriptionGroupIDEQ applies the EQ predicate on the "subscription_group_id" field.
func SubscriptionGroupIDEQ(v int64) predicate.SubscriptionPurchaseClaim {
	return predicate.SubscriptionPurchaseClaim(sql.FieldEQ(FieldSubscriptionGroupID, v))
}

// SubscriptionGroupIDNEQ applies the NEQ predicate on the "subscription_group_id" field.
func SubscriptionGroupIDNEQ(v int64) predicate.SubscriptionPurchaseClaim {
	return predicate.SubscriptionPurchaseClaim(sql.FieldNEQ(FieldSubscriptionGroupID, v))
}

// SubscriptionGroupIDIn applies the In predicate on the "subscription_group_id" field.
func SubscriptionGroupIDIn(vs ...int64) predicate.SubscriptionPurchaseClaim {
	return predicate.SubscriptionPurchaseClaim(sql.FieldIn(FieldSubscriptionGroupID, vs...))
}

// SubscriptionGroupIDNotIn applies the NotIn predicate on the "subscription_group_id" field.
func SubscriptionGroupIDNotIn(vs ...int64) predicate.SubscriptionPurchaseClaim {
	return predicate.SubscriptionPurchaseClaim(sql.FieldNotIn(FieldSubscriptionGroupID, vs...))
}

// SubscriptionGroupIDGT applies the GT predicate on the "subscription_group_id" field.
func SubscriptionGroupIDGT(v int64) predicate.SubscriptionPurchaseClaim {
	return predicate.SubscriptionPurchaseClaim(sql.FieldGT(FieldSubscriptionGroupID, v))
}

// SubscriptionGroupIDGTE applies the GTE predicate on the "subscription_group_id" field.
func SubscriptionGroupIDGTE(v int64) predicate.SubscriptionPurchaseClaim {
	return predicate.SubscriptionPurchaseClaim(sql.FieldGTE(FieldSubscriptionGroupID, v))
}

// SubscriptionGroupIDLT applies the LT predicate on the "subscription_group_id" field.
func SubscriptionGroupIDLT(v int64) predicate.SubscriptionPurchaseClaim {
	return predicate.SubscriptionPurchaseClaim(sql.FieldLT(FieldSubscriptionGroupID, v))
}

// SubscriptionGroupIDLTE applies the LTE predicate on the "subscription_group_id" field.
func SubscriptionGroupIDLTE(v int64) predicate.SubscriptionPurchaseClaim {
	return predicate.SubscriptionPurchaseClaim(sql.FieldLTE(FieldSubscriptionGroupID, v))
}

// PaymentOrderIDEQ applies the EQ predicate on the "payment_order_id" field.
func PaymentOrderIDEQ(v int64) predicate.SubscriptionPurchaseClaim {
	return predicate.SubscriptionPurchaseClaim(sql.FieldEQ(FieldPaymentOrderID, v))
}

// PaymentOrderIDNEQ applies the NEQ predicate on the "payment_order_id" field.
func PaymentOrderIDNEQ(v int64) predicate.SubscriptionPurchaseClaim {
	return predicate.SubscriptionPurchaseClaim(sql.FieldNEQ(FieldPaymentOrderID, v))
}

// PaymentOrderIDIn applies the In predicate on the "payment_order_id" field.
func PaymentOrderIDIn(vs ...int64) predicate.SubscriptionPurchaseClaim {
	return predicate.SubscriptionPurchaseClaim(sql.FieldIn(FieldPaymentOrderID, vs...))
}

// PaymentOrderIDNotIn applies the NotIn predicate on the "payment_order_id" field.
func PaymentOrderIDNotIn(vs ...int64) predicate.SubscriptionPurchaseClaim {
	return predicate.SubscriptionPurchaseClaim(sql.FieldNotIn(FieldPaymentOrderID, vs...))
}

// PaymentOrderIDGT applies the GT predicate on the "payment_order_id" field.
func PaymentOrderIDGT(v int64) predicate.SubscriptionPurchaseClaim {
	return predicate.SubscriptionPurchaseClaim(sql.FieldGT(FieldPaymentOrderID, v))
}

// PaymentOrderIDGTE applies the GTE predicate on the "payment_order_id" field.
func PaymentOrderIDGTE(v int64) predicate.SubscriptionPurchaseClaim {
	return predicate.SubscriptionPurchaseClaim(sql.FieldGTE(FieldPaymentOrderID, v))
}

// PaymentOrderIDLT applies the LT predicate on the "payment_order_id" field.
func PaymentOrderIDLT(v int64) predicate.SubscriptionPurchaseClaim {
	return predicate.SubscriptionPurchaseClaim(sql.FieldLT(FieldPaymentOrderID, v))
}

// PaymentOrderIDLTE applies the LTE predicate on the "payment_order_id" field.
func PaymentOrderIDLTE(v int64) predicate.SubscriptionPurchaseClaim {
	return predicate.SubscriptionPurchaseClaim(sql.FieldLTE(FieldPaymentOrderID, v))
}

// PaymentOrderIDIsNil applies the IsNil predicate on the "payment_order_id" field.
func PaymentOrderIDIsNil() predicate.SubscriptionPurchaseClaim {
	return predicate.SubscriptionPurchaseClaim(sql.FieldIsNull(FieldPaymentOrderID))
}

// PaymentOrderIDNotNil applies the NotNil predicate on the "payment_order_id" field.
func PaymentOrderIDNotNil() predicate.SubscriptionPurchaseClaim {
	return predicate.SubscriptionPurchaseClaim(sql.FieldNotNull(FieldPaymentOrderID))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.SubscriptionPurchaseClaim {
	return predicate.SubscriptionPurchaseClaim(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.SubscriptionPurchaseClaim {
	return predicate.SubscriptionPurchaseClaim(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.SubscriptionPurchaseClaim {
	return predicate.SubscriptionPurchaseClaim(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.SubscriptionPurchaseClaim {
	return predicate.SubscriptionPurchaseClaim(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.SubscriptionPurchaseClaim {
	return predicate.SubscriptionPurchaseClaim(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.SubscriptionPurchaseClaim {
	return predicate.SubscriptionPurchaseClaim(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.SubscriptionPurchaseClaim {
	return predicate.SubscriptionPurchaseClaim(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.SubscriptionPurchaseClaim {
	return predicate.SubscriptionPurchaseClaim(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.SubscriptionPurchaseClaim {
	return predicate.SubscriptionPurchaseClaim(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.SubscriptionPurchaseClaim {
	return predicate.SubscriptionPurchaseClaim(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.SubscriptionPurchaseClaim {
	return predicate.SubscriptionPurchaseClaim(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.SubscriptionPurchaseClaim {
	return predicate.SubscriptionPurchaseClaim(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.SubscriptionPurchaseClaim {
	return predicate.SubscriptionPurchaseClaim(sql.FieldContainsFold(FieldStatus, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.SubscriptionPurchaseClaim {
	return predicate.SubscriptionPurchaseClaim(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.SubscriptionPurchaseClaim {
	return predicate.SubscriptionPurchaseClaim(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.SubscriptionPurchaseClaim {
	return predicate.SubscriptionPurchaseClaim(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.SubscriptionPurchaseClaim {
	return predicate.SubscriptionPurchaseClaim(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.SubscriptionPurchaseClaim {
	return predicate.SubscriptionPurchaseClaim(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.SubscriptionPurchaseClaim {
	return predicate.SubscriptionPurchaseClaim(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.SubscriptionPurchaseClaim {
	return predicate.SubscriptionPurchaseClaim(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.SubscriptionPurchaseClaim {
	return predicate.SubscriptionPurchaseClaim(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.SubscriptionPurchaseClaim {
	return predicate.SubscriptionPurchaseClaim(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.SubscriptionPurchaseClaim {
	return predicate.SubscriptionPurchaseClaim(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.SubscriptionPurchaseClaim {
	return predicate.SubscriptionPurchaseClaim(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.SubscriptionPurchaseClaim {
	return predicate.SubscriptionPurchaseClaim(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.SubscriptionPurchaseClaim {
	return predicate.SubscriptionPurchaseClaim(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.SubscriptionPurchaseClaim {
	return predicate.SubscriptionPurchaseClaim(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.SubscriptionPurchaseClaim {
	return predicate.SubscriptionPurchaseClaim(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.SubscriptionPurchaseClaim {
	return predicate.SubscriptionPurchaseClaim(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.SubscriptionPurchaseClaim) predicate.SubscriptionPurchaseClaim {
	return predicate.SubscriptionPurchaseClaim(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.SubscriptionPurchaseClaim) predicate.SubscriptionPurchaseClaim {
	return predicate.SubscriptionPurchaseClaim(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.SubscriptionPurchaseClaim) predicate.SubscriptionPurchaseClaim {
	return predicate.SubscriptionPurchaseClaim(sql.NotPredicates(p))
}
